return {
	{
		Type = "Debris",
		FlipbookType = 2,
		TextureId = 18765221838
	},
	{
		Type = "Debris",
		FlipbookType = 2,
		TextureId = 18765222068
	},
	{
		Type = "Debris",
		FlipbookType = 2,
		TextureId = 12800316081
	},
	{
		Type = "Debris",
		FlipbookType = 2,
		TextureId = 12800351913
	},
	{
		Type = "Debris",
		FlipbookType = 2,
		TextureId = 132795047526276
	},
	{
		Type = "Debris",
		FlipbookType = 2,
		TextureId = 96302870857102
	},
	{
		Type = "Debris",
		FlipbookType = 2,
		TextureId = 82603403775997
	},
	{
		Type = "Debris",
		FlipbookType = 2,
		TextureId = 138004702320351
	},
	{
		Type = "Debris",
		FlipbookType = 2,
		TextureId = 80679289979548
	},
	{
		Type = "Debris",
		FlipbookType = 2,
		TextureId = 122365610446598
	},
	{
		Type = "Debris",
		FlipbookType = 2,
		TextureId = 13338673146
	},
	{
		Type = "Debris",
		FlipbookType = 2,
		TextureId = 11362067232
	},
	{
		Type = "Debris",
		FlipbookType = 2,
		TextureId = 13493209060
	},
	{
		Type = "Debris",
		FlipbookType = 2,
		TextureId = 12943289715
	},
	{
		Type = "Debris",
		FlipbookType = 2,
		TextureId = 11353163220
	},
	{
		Type = "Debris",
		FlipbookType = 2,
		TextureId = 77869930049791
	},
	{
		Type = "Debris",
		FlipbookType = 2,
		TextureId = 12800314962
	},
	{
		Type = "Debris",
		FlipbookType = 2,
		TextureId = 82581730437358
	},
	{
		Type = "Debris",
		FlipbookType = 2,
		TextureId = 12800313158
	},
	{
		Type = "Debris",
		FlipbookType = 2,
		TextureId = 12800314277
	},
	{
		Type = "Debris",
		FlipbookType = 2,
		TextureId = 12800352684
	},
	{
		Type = "Debris",
		FlipbookType = 2,
		TextureId = 12800315990
	},
	{
		Type = "Debris",
		FlipbookType = 2,
		TextureId = 12800352088
	},
	{
		Type = "Debris",
		FlipbookType = 2,
		TextureId = 120490877223652
	},
	{
		Type = "Debris",
		FlipbookType = 2,
		TextureId = 12800315821
	},
	{
		Type = "Debris",
		FlipbookType = 2,
		TextureId = 17842430380
	},
	{
		Type = "Debris",
		FlipbookType = 2,
		TextureId = 12800312871
	},
	{
		Type = "Debris",
		FlipbookType = 2,
		TextureId = 15955521232
	},
	{
		Type = "Debris",
		FlipbookType = 2,
		TextureId = 12800314151
	},
	{
		Type = "Debris",
		FlipbookType = 2,
		TextureId = 73740133306280
	},
	{
		Type = "Debris",
		FlipbookType = 2,
		TextureId = 13008210057
	},
	{
		Type = "Debris",
		FlipbookType = 2,
		TextureId = 16163096126
	},
	{
		Type = "Debris",
		FlipbookType = 2,
		TextureId = 11189071174
	},
	{
		Type = "Debris",
		FlipbookType = 2,
		TextureId = 12800312415
	},
	{
		Type = "Debris",
		FlipbookType = 2,
		TextureId = 12800314414
	},
	{
		Type = "Debris",
		FlipbookType = 2,
		TextureId = 15054104862
	},
	{
		Type = "Debris",
		FlipbookType = 2,
		TextureId = 12800315509
	},
	{
		Type = "Debris",
		FlipbookType = 2,
		TextureId = 118718250634492
	},
	{
		Type = "Debris",
		FlipbookType = 2,
		TextureId = 140255517856048
	},
	{
		Type = "Debris",
		FlipbookType = 2,
		TextureId = 74118294238291
	},
	{
		Type = "Debris",
		FlipbookType = 2,
		TextureId = 15441282898
	},
	{
		Type = "Debris",
		FlipbookType = 2,
		TextureId = 14475651883
	},
	{
		Type = "Debris",
		FlipbookType = 2,
		TextureId = 12800350363
	},
	{
		Type = "Debris",
		FlipbookType = 2,
		TextureId = 12800315318
	},
	{
		Type = "Debris",
		FlipbookType = 2,
		TextureId = 17635397469
	},
	{
		Type = "Debris",
		FlipbookType = 2,
		TextureId = 12800316456
	},
	{
		Type = "Debris",
		FlipbookType = 2,
		TextureId = 17320289910
	},
	{
		Type = "Debris",
		FlipbookType = 2,
		TextureId = 18953046796
	},
	{
		Type = "Debris",
		FlipbookType = 2,
		TextureId = 18227190925
	},
	{
		Type = "Debris",
		FlipbookType = 2,
		TextureId = 17320384006
	},
	{
		Type = "Debris",
		FlipbookType = 2,
		TextureId = 12800314611
	},
	{
		Type = "Debris",
		FlipbookType = 2,
		TextureId = 12800313372
	},
	{
		Type = "Debris",
		FlipbookType = 2,
		TextureId = 76867893491087
	},
	{
		Type = "Debris",
		FlipbookType = 2,
		TextureId = 15831917569
	},
	{
		Type = "Debris",
		FlipbookType = 2,
		TextureId = 16924521976
	},
	{
		Type = "Debris",
		FlipbookType = 2,
		TextureId = 124012488935645
	},
	{
		Type = "Debris",
		FlipbookType = 2,
		TextureId = 12800315104
	},
	{
		Type = "Debris",
		FlipbookType = 2,
		TextureId = 16661862431
	},
	{
		Type = "Debris",
		FlipbookType = 2,
		TextureId = 12800312263
	},
	{
		Type = "Debris",
		FlipbookType = 2,
		TextureId = 12181028481
	},
	{
		Type = "Debris",
		FlipbookType = 2,
		TextureId = 131631878006398
	},
	{
		Type = "Debris",
		FlipbookType = 2,
		TextureId = 12800350652
	},
	{
		Type = "Debris",
		FlipbookType = 2,
		TextureId = 12800351745
	},
	{
		Type = "Debris",
		FlipbookType = 2,
		TextureId = 18953046994
	},
	{
		Type = "Debris",
		FlipbookType = 2,
		TextureId = 139759126655001
	},
	{
		Type = "Debris",
		FlipbookType = 2,
		TextureId = 84820541525710
	},
	{
		Type = "Debris",
		FlipbookType = 2,
		TextureId = 88372363219378
	},
	{
		Type = "Debris",
		FlipbookType = 2,
		TextureId = 15810941644
	},
	{
		Type = "Debris",
		FlipbookType = 2,
		TextureId = 13393033122
	},
	{
		Type = "Debris",
		FlipbookType = 8,
		TextureId = 10547401966
	},
	{
		Type = "Debris",
		FlipbookType = 8,
		TextureId = 15416628892
	},
	{
		Type = "Debris",
		FlipbookType = 8,
		TextureId = 88301471259954
	},
	{
		Type = "Debris",
		FlipbookType = 8,
		TextureId = 10547195174
	},
	{
		Type = "Debris",
		FlipbookType = 8,
		TextureId = 15009783511
	},
	{
		Type = "Debris",
		FlipbookType = 8,
		TextureId = 14635196973
	},
	{
		Type = "Debris",
		FlipbookType = 8,
		TextureId = 100960282393192
	},
	{
		Type = "Debris",
		FlipbookType = 8,
		TextureId = 16511637718
	},
	{
		Type = "Debris",
		FlipbookType = 8,
		TextureId = 112954728779857
	},
	{
		Type = "Debris",
		FlipbookType = 8,
		TextureId = 15441239554
	},
	{
		Type = "Debris",
		FlipbookType = 8,
		TextureId = 18612948412
	},
	{
		Type = "Debris",
		FlipbookType = 8,
		TextureId = 10767898454
	},
	{
		Type = "Debris",
		FlipbookType = 8,
		TextureId = 73947304495769
	},
	{
		Type = "Debris",
		FlipbookType = 8,
		TextureId = 16511472775
	},
	{
		Type = "Debris",
		FlipbookType = 8,
		TextureId = 15960293906
	},
	{
		Type = "Debris",
		FlipbookType = 8,
		TextureId = 16511867845
	},
	{
		Type = "Debris",
		FlipbookType = 8,
		TextureId = 87790026409442
	},
	{
		Type = "Debris",
		FlipbookType = 8,
		TextureId = 16511766235
	},
	{
		Type = "Debris",
		FlipbookType = 8,
		TextureId = 15317802227
	},
	{
		Type = "Debris",
		FlipbookType = 8,
		TextureId = 84698819517635
	},
	{
		Type = "Debris",
		FlipbookType = 8,
		TextureId = 16511173887
	},
	{
		Type = "Debris",
		FlipbookType = 8,
		TextureId = 15952530545
	},
	{
		Type = "Debris",
		FlipbookType = 8,
		TextureId = 15406411553
	},
	{
		Type = "Debris",
		FlipbookType = 8,
		TextureId = 9293679454
	},
	{
		Type = "Debris",
		FlipbookType = 8,
		TextureId = 16511616455
	},
	{
		Type = "Debris",
		FlipbookType = 8,
		TextureId = 13487538321
	},
	{
		Type = "Debris",
		FlipbookType = 8,
		TextureId = 12169768457
	},
	{
		Type = "Debris",
		FlipbookType = 8,
		TextureId = 14471362207
	},
	{
		Type = "Debris",
		FlipbookType = 8,
		TextureId = 16511298384
	},
	{
		Type = "Debris",
		FlipbookType = 8,
		TextureId = 15011297518
	},
	{
		Type = "Debris",
		FlipbookType = 8,
		TextureId = 17635379154
	},
	{
		Type = "Debris",
		FlipbookType = 8,
		TextureId = 17635389125
	},
	{
		Type = "Debris",
		FlipbookType = 8,
		TextureId = 12311602739
	},
	{
		Type = "Debris",
		FlipbookType = 8,
		TextureId = 14197086122
	},
	{
		Type = "Debris",
		FlipbookType = 8,
		TextureId = 123254584335732
	},
	{
		Type = "Debris",
		FlipbookType = 8,
		TextureId = 71298374838414
	},
	{
		Type = "Debris",
		FlipbookType = 8,
		TextureId = 10767784446
	},
	{
		Type = "Debris",
		FlipbookType = 8,
		TextureId = 17635399275
	},
	{
		Type = "Debris",
		FlipbookType = 8,
		TextureId = 16511071584
	},
	{
		Type = "Debris",
		FlipbookType = 8,
		TextureId = 117546343821485
	},
	{
		Type = "Debris",
		FlipbookType = 8,
		TextureId = 12250428891
	},
	{
		Type = "Debris",
		FlipbookType = 8,
		TextureId = 15441262724
	},
	{
		Type = "Debris",
		FlipbookType = 8,
		TextureId = 136219222277983
	},
	{
		Type = "Debris",
		FlipbookType = 8,
		TextureId = 13803462600
	},
	{
		Type = "Debris",
		FlipbookType = 8,
		TextureId = 16511446679
	},
	{
		Type = "Debris",
		FlipbookType = 8,
		TextureId = 79053843420399
	},
	{
		Type = "Debris",
		FlipbookType = 8,
		TextureId = 14197139100
	},
	{
		Type = "Debris",
		FlipbookType = 8,
		TextureId = 14200333672
	},
	{
		Type = "Debris",
		FlipbookType = 8,
		TextureId = 15955838061
	},
	{
		Type = "Debris",
		FlipbookType = 8,
		TextureId = 17509925790
	},
	{
		Type = "Debris",
		FlipbookType = 8,
		TextureId = 11817592243
	},
	{
		Type = "Debris",
		FlipbookType = 8,
		TextureId = 14079007947
	},
	{
		Type = "Debris",
		FlipbookType = 8,
		TextureId = 16512031962
	},
	{
		Type = "Debris",
		FlipbookType = 8,
		TextureId = 101064921051567
	},
	{
		Type = "Debris",
		FlipbookType = 8,
		TextureId = 122651268609324
	},
	{
		Type = "Debris",
		FlipbookType = 8,
		TextureId = 15270321746
	},
	{
		Type = "Debris",
		FlipbookType = 8,
		TextureId = 12285599556
	},
	{
		Type = "Debris",
		FlipbookType = 8,
		TextureId = 16501229582
	},
	{
		Type = "Debris",
		FlipbookType = 8,
		TextureId = 91823330391749
	},
	{
		Type = "Debris",
		FlipbookType = 8,
		TextureId = 13803008213
	},
	{
		Type = "Debris",
		FlipbookType = 8,
		TextureId = 121437183202003
	},
	{
		Type = "Debris",
		FlipbookType = 8,
		TextureId = 15011464541
	},
	{
		Type = "Debris",
		FlipbookType = 8,
		TextureId = 11726473936
	},
	{
		Type = "Debris",
		FlipbookType = 8,
		TextureId = 16879591102
	},
	{
		Type = "Debris",
		FlipbookType = 8,
		TextureId = 17096211053
	},
	{
		Type = "Debris",
		FlipbookType = 8,
		TextureId = 16511093402
	},
	{
		Type = "Debris",
		FlipbookType = 8,
		TextureId = 14197083420
	},
	{
		Type = "Debris",
		FlipbookType = 8,
		TextureId = 18612952437
	},
	{
		Type = "Debris",
		FlipbookType = 8,
		TextureId = 15845909331
	},
	{
		Type = "Debris",
		FlipbookType = 8,
		TextureId = 16511541267
	},
	{
		Type = "Debris",
		FlipbookType = 8,
		TextureId = 16511853407
	},
	{
		Type = "Debris",
		FlipbookType = 8,
		TextureId = 12231042454
	},
	{
		Type = "Debris",
		FlipbookType = 8,
		TextureId = 16510916342
	},
	{
		Type = "Debris",
		FlipbookType = 8,
		TextureId = 15841621175
	},
	{
		Type = "Debris",
		FlipbookType = 8,
		TextureId = 17635401139
	},
	{
		Type = "Debris",
		FlipbookType = 8,
		TextureId = 13803331652
	},
	{
		Type = "Debris",
		FlipbookType = 8,
		TextureId = 16924962354
	},
	{
		Type = "Debris",
		FlipbookType = 8,
		TextureId = 16519759327
	},
	{
		Type = "Debris",
		FlipbookType = 8,
		TextureId = 140718057216444
	},
	{
		Type = "Debris",
		FlipbookType = 8,
		TextureId = 128169567521803
	},
	{
		Type = "Debris",
		FlipbookType = 8,
		TextureId = 14261754295
	},
	{
		Type = "Debris",
		FlipbookType = 8,
		TextureId = 13448499301
	},
	{
		Type = "Debris",
		FlipbookType = 8,
		TextureId = 14967667787
	},
	{
		Type = "Debris",
		FlipbookType = 8,
		TextureId = 115162635802910
	},
	{
		Type = "Debris",
		FlipbookType = 8,
		TextureId = 89169149094251
	},
	{
		Type = "Debris",
		FlipbookType = 4,
		TextureId = 14967834190
	},
	{
		Type = "Debris",
		FlipbookType = 4,
		TextureId = 11373300948
	},
	{
		Type = "Debris",
		FlipbookType = 4,
		TextureId = 13470068974
	},
	{
		Type = "Debris",
		FlipbookType = 4,
		TextureId = 11762818558
	},
	{
		Type = "Debris",
		FlipbookType = 4,
		TextureId = 15703772837
	},
	{
		Type = "Debris",
		FlipbookType = 4,
		TextureId = 11702140411
	},
	{
		Type = "Debris",
		FlipbookType = 4,
		TextureId = 14985053168
	},
	{
		Type = "Debris",
		FlipbookType = 4,
		TextureId = 14164156363
	},
	{
		Type = "Debris",
		FlipbookType = 4,
		TextureId = 13820615564
	},
	{
		Type = "Debris",
		FlipbookType = 4,
		TextureId = 15657357309
	},
	{
		Type = "Debris",
		FlipbookType = 4,
		TextureId = 16924869176
	},
	{
		Type = "Debris",
		FlipbookType = 4,
		TextureId = 14128969222
	},
	{
		Type = "Debris",
		FlipbookType = 4,
		TextureId = 16924894708
	},
	{
		Type = "Debris",
		FlipbookType = 4,
		TextureId = 8733226116
	},
	{
		Type = "Debris",
		FlipbookType = 4,
		TextureId = 18765221641
	},
	{
		Type = "Debris",
		FlipbookType = 4,
		TextureId = 16056965573
	},
	{
		Type = "Debris",
		FlipbookType = 4,
		TextureId = 13528074773
	},
	{
		Type = "Debris",
		FlipbookType = 4,
		TextureId = 12807576476
	},
	{
		Type = "Debris",
		FlipbookType = 4,
		TextureId = 13388204057
	},
	{
		Type = "Debris",
		FlipbookType = 4,
		TextureId = 16504098653
	},
	{
		Type = "Debris",
		FlipbookType = 4,
		TextureId = 98618135145428
	},
	{
		Type = "Debris",
		FlipbookType = 4,
		TextureId = 8733488500
	},
	{
		Type = "Debris",
		FlipbookType = 4,
		TextureId = 16848288027
	},
	{
		Type = "Debris",
		FlipbookType = 4,
		TextureId = 16056966102
	},
	{
		Type = "Debris",
		FlipbookType = 4,
		TextureId = 14454142105
	},
	{
		Type = "Debris",
		FlipbookType = 4,
		TextureId = 15398180787
	},
	{
		Type = "Debris",
		FlipbookType = 4,
		TextureId = 13528075510
	},
	{
		Type = "Debris",
		FlipbookType = 4,
		TextureId = 12939163871
	},
	{
		Type = "Debris",
		FlipbookType = 4,
		TextureId = 13762974205
	},
	{
		Type = "Debris",
		FlipbookType = 4,
		TextureId = 13763005781
	},
	{
		Type = "Debris",
		FlipbookType = 4,
		TextureId = 13931232259
	},
	{
		Type = "Debris",
		FlipbookType = 4,
		TextureId = 90807635587191
	},
	{
		Type = "Debris",
		FlipbookType = 4,
		TextureId = 13762623803
	},
	{
		Type = "Debris",
		FlipbookType = 4,
		TextureId = 13521398126
	},
	{
		Type = "Debris",
		FlipbookType = 4,
		TextureId = 138209242993782
	},
	{
		Type = "Debris",
		FlipbookType = 4,
		TextureId = 9928796106
	},
	{
		Type = "Debris",
		FlipbookType = 4,
		TextureId = 11791539527
	},
	{
		Type = "Debris",
		FlipbookType = 4,
		TextureId = 116467238228309
	},
	{
		Type = "Debris",
		FlipbookType = 4,
		TextureId = 106087320867193
	},
	{
		Type = "Debris",
		FlipbookType = 4,
		TextureId = 99669707242220
	},
	{
		Type = "Debris",
		FlipbookType = 4,
		TextureId = 84756510201521
	},
	{
		Type = "Debris",
		FlipbookType = 4,
		TextureId = 13528076463
	},
	{
		Type = "Debris",
		FlipbookType = 4,
		TextureId = 8733666206
	},
	{
		Type = "Debris",
		FlipbookType = 4,
		TextureId = 16034517924
	},
	{
		Type = "Debris",
		FlipbookType = 4,
		TextureId = 13580365782
	},
	{
		Type = "Debris",
		FlipbookType = 4,
		TextureId = 84675755286036
	},
	{
		Type = "Debris",
		FlipbookType = 4,
		TextureId = 106607960731042
	},
	{
		Type = "Debris",
		FlipbookType = 4,
		TextureId = 102541977737859
	},
	{
		Type = "Debris",
		FlipbookType = 4,
		TextureId = 132799872893839
	},
	{
		Type = "Debris",
		FlipbookType = 4,
		TextureId = 15725639515
	},
	{
		Type = "Debris",
		FlipbookType = 4,
		TextureId = 15011474319
	},
	{
		Type = "Debris",
		FlipbookType = 4,
		TextureId = 126275989641021
	},
	{
		Type = "Debris",
		FlipbookType = 4,
		TextureId = 86661686280797
	},
	{
		Type = "Debris",
		FlipbookType = 4,
		TextureId = 136362935142359
	},
	{
		Type = "Debris",
		FlipbookType = 4,
		TextureId = 89116956652289
	},
	{
		Type = "Debris",
		FlipbookType = 4,
		TextureId = 15371082237
	},
	{
		Type = "Debris",
		FlipbookType = 4,
		TextureId = 16047072510
	},
	{
		Type = "Debris",
		FlipbookType = 4,
		TextureId = 12250162061
	},
	{
		Type = "Debris",
		FlipbookType = 4,
		TextureId = 8733731095
	},
	{
		Type = "Debris",
		FlipbookType = 4,
		TextureId = 13935212823
	},
	{
		Type = "Debris",
		FlipbookType = 4,
		TextureId = 15418442509
	},
	{
		Type = "Debris",
		FlipbookType = 4,
		TextureId = 15398107645
	},
	{
		Type = "Debris",
		FlipbookType = 4,
		TextureId = 15190793821
	},
	{
		Type = "Debris",
		FlipbookType = 4,
		TextureId = 138061581256149
	},
	{
		Type = "Debris",
		FlipbookType = 4,
		TextureId = 15810715806
	},
	{
		Type = "Debris",
		FlipbookType = 4,
		TextureId = 90909109192803
	},
	{
		Type = "Debris",
		FlipbookType = 4,
		TextureId = 131946373681101
	},
	{
		Type = "Debris",
		FlipbookType = 4,
		TextureId = 16047618456
	},
	{
		Type = "Debris",
		FlipbookType = 4,
		TextureId = 13975880803
	},
	{
		Type = "Debris",
		FlipbookType = 4,
		TextureId = 9930688951
	},
	{
		Type = "Debris",
		FlipbookType = 4,
		TextureId = 17522343420
	},
	{
		Type = "Debris",
		FlipbookType = 4,
		TextureId = 14354336687
	},
	{
		Type = "Debris",
		FlipbookType = 4,
		TextureId = 14184221370
	},
	{
		Type = "Debris",
		FlipbookType = 4,
		TextureId = 14162656592
	},
	{
		Type = "Debris",
		FlipbookType = 4,
		TextureId = 17635380117
	},
	{
		Type = "Debris",
		FlipbookType = 4,
		TextureId = 11499447365
	},
	{
		Type = "Debris",
		FlipbookType = 4,
		TextureId = 13819794054
	},
	{
		Type = "Debris",
		FlipbookType = 4,
		TextureId = 12868547034
	},
	{
		Type = "Debris",
		FlipbookType = 4,
		TextureId = 15371144313
	},
	{
		Type = "Debris",
		FlipbookType = 4,
		TextureId = 12800314817
	},
	{
		Type = "Debris",
		FlipbookType = 4,
		TextureId = 13261053113
	},
	{
		Type = "Debris",
		FlipbookType = 4,
		TextureId = 15550340138
	},
	{
		Type = "Debris",
		FlipbookType = 4,
		TextureId = 16915028648
	},
	{
		Type = "Debris",
		FlipbookType = 4,
		TextureId = 16771418430
	},
	{
		Type = "Debris",
		FlipbookType = 4,
		TextureId = 17635381231
	},
	{
		Type = "Debris",
		FlipbookType = 4,
		TextureId = 15691415178
	},
	{
		Type = "Debris",
		FlipbookType = 4,
		TextureId = 18226771810
	},
	{
		Type = "Debris",
		FlipbookType = 4,
		TextureId = 16645585416
	},
	{
		Type = "Debris",
		FlipbookType = 4,
		TextureId = 17635383223
	},
	{
		Type = "Debris",
		FlipbookType = 4,
		TextureId = 15011456461
	},
	{
		Type = "Debris",
		FlipbookType = 4,
		TextureId = 16847138652
	},
	{
		Type = "Debris",
		FlipbookType = 4,
		TextureId = 11864126298
	},
	{
		Type = "Debris",
		FlipbookType = 4,
		TextureId = 13486412595
	},
	{
		Type = "Debris",
		FlipbookType = 4,
		TextureId = 18763982109
	},
	{
		Type = "Debris",
		FlipbookType = 4,
		TextureId = 104933213624042
	},
	{
		Type = "Debris",
		FlipbookType = 4,
		TextureId = 11862051043
	},
	{
		Type = "Debris",
		FlipbookType = 4,
		TextureId = 16845044603
	},
	{
		Type = "Debris",
		FlipbookType = 4,
		TextureId = 119136869476760
	},
	{
		Type = "Debris",
		FlipbookType = 4,
		TextureId = 89985994741496
	},
	{
		Type = "Debris",
		FlipbookType = 4,
		TextureId = 12516220096
	},
	{
		Type = "Debris",
		FlipbookType = 4,
		TextureId = 129871600983536
	},
	{
		Type = "Debris",
		FlipbookType = 4,
		TextureId = 111395970734311
	},
	{
		Type = "Debris",
		FlipbookType = 4,
		TextureId = 88405378022930
	},
	{
		Type = "Debris",
		FlipbookType = 4,
		TextureId = 16504008650
	},
	{
		Type = "Debris",
		FlipbookType = 4,
		TextureId = 15892769449
	},
	{
		Type = "Debris",
		FlipbookType = 4,
		TextureId = 14068947349
	},
	{
		Type = "Debris",
		FlipbookType = 4,
		TextureId = 17005474307
	},
	{
		Type = "Debris",
		FlipbookType = 4,
		TextureId = 11492870634
	},
	{
		Type = "Debris",
		FlipbookType = 4,
		TextureId = 16924751496
	},
	{
		Type = "Debris",
		FlipbookType = 4,
		TextureId = 134173419652080
	},
	{
		Type = "Debris",
		FlipbookType = 4,
		TextureId = 16503257599
	},
	{
		Type = "Debris",
		FlipbookType = 4,
		TextureId = 12094495797
	},
	{
		Type = "Debris",
		FlipbookType = 4,
		TextureId = 11802275950
	},
	{
		Type = "Debris",
		FlipbookType = 4,
		TextureId = 14219717388
	},
	{
		Type = "Debris",
		FlipbookType = 4,
		TextureId = 14568623802
	},
	{
		Type = "Debris",
		FlipbookType = 4,
		TextureId = 14389608930
	},
	{
		Type = "Debris",
		FlipbookType = 4,
		TextureId = 117237341935346
	},
	{
		Type = "Debris",
		FlipbookType = 4,
		TextureId = 8733226116
	},
	{
		Type = "Debris",
		FlipbookType = 4,
		TextureId = 11862032588
	},
	{
		Type = "Debris",
		FlipbookType = 4,
		TextureId = 72375049001796
	},
	{
		Type = "Debris",
		FlipbookType = 4,
		TextureId = 12853318983
	},
	{
		Type = "Debris",
		FlipbookType = 4,
		TextureId = 13670411508
	},
	{
		Type = "Debris",
		FlipbookType = 4,
		TextureId = 122736820304816
	},
	{
		Type = "Debris",
		FlipbookType = 4,
		TextureId = 13778464872
	},
	{
		Type = "Debris",
		FlipbookType = 4,
		TextureId = 13973317169
	},
	{
		Type = "Debris",
		FlipbookType = 4,
		TextureId = 16510079563
	},
	{
		Type = "Debris",
		FlipbookType = 4,
		TextureId = 9499725747
	},
	{
		Type = "Debris",
		FlipbookType = 4,
		TextureId = 13463784319
	},
	{
		Type = "Debris",
		FlipbookType = 4,
		TextureId = 125815493686333
	},
	{
		Type = "Debris",
		FlipbookType = 4,
		TextureId = 9147379744
	},
	{
		Type = "Debris",
		FlipbookType = 4,
		TextureId = 13321919628
	},
	{
		Type = "Debris",
		FlipbookType = 4,
		TextureId = 87027646041948
	},
	{
		Type = "Debris",
		FlipbookType = 4,
		TextureId = 15059553660
	},
	{
		Type = "Debris",
		FlipbookType = 4,
		TextureId = 16879595559
	},
	{
		Type = "Debris",
		FlipbookType = 4,
		TextureId = 15810777518
	},
	{
		Type = "Debris",
		FlipbookType = 4,
		TextureId = 138353277257048
	},
	{
		Type = "Debris",
		FlipbookType = 4,
		TextureId = 18761488246
	},
	{
		Type = "Debris",
		FlipbookType = 4,
		TextureId = 11622450564
	},
	{
		Type = "Debris",
		FlipbookType = 4,
		TextureId = 13780092154
	},
	{
		Type = "Debris",
		FlipbookType = 4,
		TextureId = 115846753587357
	},
	{
		Type = "Debris",
		FlipbookType = 4,
		TextureId = 14367526987
	},
	{
		Type = "Debris",
		FlipbookType = 4,
		TextureId = 14004161351
	},
	{
		Type = "Debris",
		FlipbookType = 4,
		TextureId = 10258532371
	},
	{
		Type = "Debris",
		FlipbookType = 4,
		TextureId = 15371144313
	},
	{
		Type = "Debris",
		FlipbookType = 4,
		TextureId = 15719960552
	},
	{
		Type = "Debris",
		FlipbookType = 4,
		TextureId = 98916377687042
	},
	{
		Type = "Debris",
		FlipbookType = 4,
		TextureId = 13390196434
	},
	{
		Type = "Debris",
		FlipbookType = 4,
		TextureId = 71152974359183
	},
	{
		Type = "Debris",
		FlipbookType = 4,
		TextureId = 83109627968100
	},
	{
		Type = "Debris",
		FlipbookType = 4,
		TextureId = 17125333780
	},
	{
		Type = "Debris",
		FlipbookType = 4,
		TextureId = 110544581884796
	},
	{
		Type = "Debris",
		FlipbookType = 4,
		TextureId = 14221318481
	},
	{
		Type = "Debris",
		FlipbookType = 4,
		TextureId = 9143341648
	},
	{
		Type = "Debris",
		FlipbookType = 4,
		TextureId = 16504812196
	},
	{
		Type = "Debris",
		FlipbookType = 4,
		TextureId = 137903763628085
	},
	{
		Type = "Debris",
		FlipbookType = 4,
		TextureId = 18569840034
	},
	{
		Type = "Debris",
		FlipbookType = 4,
		TextureId = 16511741323
	},
	{
		Type = "Debris",
		FlipbookType = 4,
		TextureId = 9173494396
	},
	{
		Type = "Debris",
		FlipbookType = 4,
		TextureId = 111400561857268
	},
	{
		Type = "Debris",
		FlipbookType = 4,
		TextureId = 16513631527
	},
	{
		Type = "Debris",
		FlipbookType = 4,
		TextureId = 17125348936
	},
	{
		Type = "Debris",
		FlipbookType = 4,
		TextureId = 16924740376
	},
	{
		Type = "Debris",
		FlipbookType = 4,
		TextureId = 13922098740
	},
	{
		Type = "Debris",
		FlipbookType = 4,
		TextureId = 13209151224
	},
	{
		Type = "Debris",
		FlipbookType = 4,
		TextureId = 16433757077
	},
	{
		Type = "Debris",
		FlipbookType = 4,
		TextureId = 115137443384625
	},
	{
		Type = "Debris",
		FlipbookType = 4,
		TextureId = 16504113471
	},
	{
		Type = "Debris",
		FlipbookType = 4,
		TextureId = 121409713377737
	},
	{
		Type = "Debris",
		FlipbookType = 4,
		TextureId = 112664491606298
	},
	{
		Type = "Debris",
		FlipbookType = 4,
		TextureId = 16504247789
	},
	{
		Type = "Debris",
		FlipbookType = 4,
		TextureId = 16645592721
	},
	{
		Type = "Debris",
		FlipbookType = 4,
		TextureId = 10713705343
	},
	{
		Type = "Debris",
		FlipbookType = 4,
		TextureId = 14431633138
	},
	{
		Type = "Debris",
		FlipbookType = 4,
		TextureId = 13378753362
	},
	{
		Type = "Debris",
		FlipbookType = 4,
		TextureId = 13778471930
	},
	{
		Type = "Debris",
		FlipbookType = 4,
		TextureId = 102317868535511
	},
	{
		Type = "Debris",
		FlipbookType = 4,
		TextureId = 17426863133
	},
	{
		Type = "Debris",
		FlipbookType = 4,
		TextureId = 15102717966
	},
	{
		Type = "Debris",
		FlipbookType = 4,
		TextureId = 81674353181881
	},
	{
		Type = "Debris",
		FlipbookType = 4,
		TextureId = 11349507100
	},
	{
		Type = "Debris",
		FlipbookType = 4,
		TextureId = 71372784229027
	},
	{
		Type = "Debris",
		FlipbookType = 4,
		TextureId = 16034333422
	},
	{
		Type = "Debris",
		FlipbookType = 4,
		TextureId = 16430855742
	},
	{
		Type = "Debris",
		FlipbookType = 4,
		TextureId = 16693839254
	},
	{
		Type = "Debris",
		FlipbookType = 4,
		TextureId = 14305019062
	},
	{
		Type = "Debris",
		FlipbookType = 4,
		TextureId = 11373281038
	},
	{
		Type = "Debris",
		FlipbookType = 4,
		TextureId = 14707966237
	},
	{
		Type = "Debris",
		FlipbookType = 4,
		TextureId = 17635385037
	},
	{
		Type = "Debris",
		FlipbookType = 4,
		TextureId = 12800350244
	},
	{
		Type = "Debris",
		FlipbookType = 4,
		TextureId = 12376549723
	},
	{
		Type = "Debris",
		FlipbookType = 4,
		TextureId = 109732628845362
	},
	{
		Type = "Debris",
		FlipbookType = 4,
		TextureId = 91858024979636
	},
	{
		Type = "Debris",
		FlipbookType = 4,
		TextureId = 16924875355
	},
	{
		Type = "Debris",
		FlipbookType = 4,
		TextureId = 138623883509124
	},
	{
		Type = "Debris",
		FlipbookType = 4,
		TextureId = 17451596749
	},
	{
		Type = "Debris",
		FlipbookType = 4,
		TextureId = 14194680110
	},
	{
		Type = "Debris",
		FlipbookType = 4,
		TextureId = 99247083637599
	},
	{
		Type = "Debris",
		FlipbookType = 4,
		TextureId = 13800702582
	},
	{
		Type = "Debris",
		FlipbookType = 4,
		TextureId = 127778528880153
	},
	{
		Type = "Debris",
		FlipbookType = 4,
		TextureId = 91376672353710
	},
	{
		Type = "Debris",
		FlipbookType = 4,
		TextureId = 134688272859101
	},
	{
		Type = "Debris",
		FlipbookType = 4,
		TextureId = 14194667932
	},
	{
		Type = "Debris",
		FlipbookType = 4,
		TextureId = 119329066636427
	},
	{
		Type = "Debris",
		FlipbookType = 4,
		TextureId = 125214381397274
	},
	{
		Type = "Debris",
		FlipbookType = 4,
		TextureId = 9147387925
	},
	{
		Type = "Debris",
		FlipbookType = 4,
		TextureId = 13802408466
	},
	{
		Type = "Debris",
		FlipbookType = 4,
		TextureId = 15553173363
	},
	{
		Type = "Debris",
		FlipbookType = 4,
		TextureId = 18921681258
	},
	{
		Type = "Debris",
		FlipbookType = 4,
		TextureId = 17006091734
	},
	{
		Type = "Debris",
		FlipbookType = 4,
		TextureId = 17635395659
	},
	{
		Type = "Debris",
		FlipbookType = 4,
		TextureId = 17517655824
	},
	{
		Type = "Debris",
		FlipbookType = 4,
		TextureId = 82608837273553
	},
	{
		Type = "Debris",
		FlipbookType = 4,
		TextureId = 17612133760
	},
	{
		Type = "Debris",
		FlipbookType = 4,
		TextureId = 127905207342396
	},
	{
		Type = "Debris",
		FlipbookType = 4,
		TextureId = 15826927544
	},
	{
		Type = "Debris",
		FlipbookType = 4,
		TextureId = 116500327780393
	},
	{
		Type = "Debris",
		FlipbookType = 4,
		TextureId = 17635387087
	},
	{
		Type = "Debris",
		FlipbookType = 4,
		TextureId = 80103775847743
	},
	{
		Type = "Debris",
		FlipbookType = 4,
		TextureId = 11910560348
	},
	{
		Type = "Debris",
		FlipbookType = 4,
		TextureId = 16502428362
	},
	{
		Type = "Debris",
		FlipbookType = 4,
		TextureId = 134905651699770
	},
	{
		Type = "Debris",
		FlipbookType = 4,
		TextureId = 18765294301
	},
	{
		Type = "Debris",
		FlipbookType = 4,
		TextureId = 15659089816
	},
	{
		Type = "Debris",
		FlipbookType = 4,
		TextureId = 16056964777
	},
	{
		Type = "Debris",
		FlipbookType = 4,
		TextureId = 13243734535
	},
	{
		Type = "Debris",
		FlipbookType = 4,
		TextureId = 88465303352145
	},
	{
		Type = "Debris",
		FlipbookType = 4,
		TextureId = 17635402158
	},
	{
		Type = "Debris",
		FlipbookType = 4,
		TextureId = 18306688920
	},
	{
		Type = "Debris",
		FlipbookType = 4,
		TextureId = 105000807688628
	},
	{
		Type = "Debris",
		FlipbookType = 4,
		TextureId = 13580373013
	},
	{
		Type = "Debris",
		FlipbookType = 4,
		TextureId = 13992224965
	},
	{
		Type = "Debris",
		FlipbookType = 4,
		TextureId = 13456395744
	}
}
