return {
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 125780429587180
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 301261210
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 6053278241
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 1463939561
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 9533204395
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 15955933046
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 108463674494908
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 12713359009
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 13388197609
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 882168791
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 9377181444
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 7216850429
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 11316960161
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 851544940
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 12745412435
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 6947810416
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 13580361273
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 17635102637
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 135407002016092
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 8944142619
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 8944136294
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 8944140815
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 13271148125
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 17635115017
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 10545078665
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 12745435209
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 17635112304
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 17635104177
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 8187306179
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 16034453852
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 7447854952
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 281639817
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 8133326767
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 6602421253
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 5655747881
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 17511074515
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 1084976679
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 11037547494
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 76424859299967
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 14919963322
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 98684562331075
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 17634908943
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 15419159687
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 17634904515
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 15940170338
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 13712002093
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 17635108768
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 914595092
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 17354353102
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 6947809971
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 18227621394
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 17635991043
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 6820680001
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 15419184068
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 17635110547
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 17635105742
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 16924983832
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 17634884839
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 15419162584
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 17459563854
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 17635008753
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 13875044490
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 17635107368
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 17334135713
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 15419187870
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 121602418371942
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 126676554564576
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 7294479235
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 1084997326
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 1084996976
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 82247757962533
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 8944218470
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 6766245698
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 8511527728
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 14734980747
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 1084969783
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 17635056733
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 12492886420
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 15989904878
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 8922788417
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 12251477957
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 15394196527
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 11448304274
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 15419190662
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 17634950701
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 17635048474
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 13811857635
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 15419163160
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 17634782784
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 14199216697
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 10953167939
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 290833005
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 13047163430
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 1262993978
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 15658580283
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 18454278255
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 15419166595
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 14198039702
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 10976611540
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 12781881514
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 11037284963
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 13400488559
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 9533203298
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 17496611372
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 1084959583
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 112443398099861
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 131743246951652
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 15419186182
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 12942158384
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 13712002093
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 12728118638
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 15419189769
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 12386382494
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 8187307323
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 7511321694
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 13271125201
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 13295203227
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 7264950759
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 131883327089412
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 18446116252
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 16879804431
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 14007518610
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 12656836563
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 17635053216
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 18836694007
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 118243636520967
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 106053714897877
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 16995731379
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 14216651706
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 10976580763
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 12222002958
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 1084959312
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 18765290302
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 1084959112
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 36721240
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 18450596124
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 15419187362
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 2719787647
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 16924475420
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 13161948501
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 15419187058
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 14054642335
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 17634897891
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 16411214655
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 12356780938
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 15887200134
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 122662949386396
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 139973134096587
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 15231485249
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 91455177206655
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 8114157061
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 1851669703
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 127583435334430
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 12402879882
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 12402856027
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 917188138
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 7998769262
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 304113188
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 16310675101
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 8223451413
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 7495374889
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 18539291909
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 15419163675
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 14608917498
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 11891936366
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 16617576736
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 7216855813
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 108671638834303
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 15142050539
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 111373806976574
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 7216855695
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 275871881
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 7216854681
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 17404846378
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 5602763719
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 8612024759
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 173642823
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 7216855595
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 14198059051
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 136058563164321
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 113398526623218
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 1349050856
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 281633012
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 13366456630
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 18450653938
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 14844074205
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 13887114225
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 17671384084
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 6475162564
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 7858295963
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 15419189376
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 8030839542
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 10205180639
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 73547327
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 11862493383
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 17496614564
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 6369896729
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 12556256482
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 16505028339
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 15419189018
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 6354867625
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 14261327670
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 14198040720
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 14128174788
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 121618537304768
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 15824423571
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 243665208
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 17634891284
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 8944384590
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 11724377368
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 480483982
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 84484878548223
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 6700009498
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 8944190351
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 5789352409
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 243043091
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 16276176220
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 13249421392
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 7216979305
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 8271975883
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 7216979617
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 96766107101865
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 17634911556
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 17634871742
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 7216979807
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 8399529129
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 11192614305
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 15024914905
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 15394194008
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 15268229875
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 241717907
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 17634869173
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 7216979420
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 15264803886
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 7216979191
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 17635433203
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 17634892451
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 17635007355
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 9841300824
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 103703334016211
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 9449395070
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 8084996370
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 17634877172
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 15419185068
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 17634779376
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 13366419059
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 90699600186298
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 17420203602
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 9841260273
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 16171607099
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 17635213348
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 7216847852
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 6700008769
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 15419188636
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 243664729
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 11201546023
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 13548310351
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 7352930328
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 12681270997
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 15431912045
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 87160246794036
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 6820821916
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 8698793845
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 8242018934
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 6955806741
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 1084961641
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 11114688219
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 8944192989
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 17634760867
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 13580350953
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 8187305869
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 9470888178
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 17634772738
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 13280154167
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 8187306008
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 8663057988
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 9657526205
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 13528080351
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 6602413638
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 8617740974
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 463053074
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 17653963471
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 7245988767
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 243098098
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 13417032203
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 14198018713
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 8944388233
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 17634800152
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 1053548563
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 8187306423
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 6955757898
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 243043229
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 11724375558
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 15268223354
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 8944381800
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 6963246544
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 11724382323
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 5100964563
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 17634769147
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 16358209603
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 17635064220
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 17635059091
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 17634912304
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 7443214314
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 80742887810818
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 13828261486
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 14128173698
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 16171528032
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 8698794520
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 5889875399
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 17634777363
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 3511307225
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 7145698111
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 15419160032
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 17635079638
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 17634775412
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 17420272060
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 6444340454
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 16879795021
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 7579361036
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 917181007
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 15419164985
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 17635162959
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 14162128187
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 10233836498
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 17635149913
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 11226108137
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 17634780647
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 7483357409
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 8133845150
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 11392234336
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 13919778556
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 17634874417
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 17634896652
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 243160943
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 346519018
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 8071207852
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 14197943648
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 133778217916173
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 17634785131
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 101253048007742
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 7443149303
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 14438046728
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 15638729672
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 6820821916
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 17635055599
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 7843470203
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 419625073
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 13276329894
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 130594856614032
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 78390022776249
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 7216848307
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 9997556038
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 109409005018110
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 17634787619
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 7216848219
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 7216848149
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 10614304526
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 16303600564
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 16924356946
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 15419162005
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 13712001736
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 17671394210
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 17634873062
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 17634770797
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 15264806770
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 17635113715
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 18453368738
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 8030734851
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 12386363554
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 14198026924
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 5697446711
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 15419164410
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 8090715771
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 15232727384
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 7845168136
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 17635050159
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 17634774159
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 7814053668
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 12505327959
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 12402856928
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 7216979522
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 15268228591
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 12572542650
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 8187306581
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 17634880702
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 16924383752
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 8944395873
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 8944393458
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 17635060489
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 11724381115
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 15419166109
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 15419188347
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 17634889439
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 18452666305
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 12598279413
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 5076152048
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 11037489528
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 135565757885099
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 12402890241
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 569507642
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 17635052094
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 569507523
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 17635006393
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 1315202524
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 7246982406
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 15267598529
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 11736666805
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 14242243419
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 7948615986
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 6963246954
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 6660412891
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 7245682360
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 1084974286
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 9799262426
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 16310640308
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 14221378803
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 7948621618
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 17634795810
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 17634895617
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 17634901233
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 17634883435
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 17634899423
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 1441759122
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 12402857904
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 14992689187
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 15268231020
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 14346169397
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 14162753420
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 15554697103
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 14198056286
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 88676678046192
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 15394198783
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 9409091712
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 14138354994
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 12482525722
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 13839776497
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 17671381935
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 915916073
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 8520264181
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 10395250849
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 16034414651
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 2545904564
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 9841300565
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 13425486384
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 14524112040
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 15419190159
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 8611887361
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 15441153502
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 117452765214067
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 17511015942
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 6963247592
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 16879789169
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 187823474
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 8238126392
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 18146792271
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 6763809313
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 12160798454
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 5210454496
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 243664672
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 4509687978
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 8708637750
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 9841301023
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 13712004045
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 8944398993
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 8944391058
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 11724373770
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 278520320
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 11724383572
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 8030760338
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 14274978490
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 284205403
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 13899344931
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 16878181512
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 567497792
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 81313628452707
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 13425686092
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 8788474862
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 9841273544
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 2065087059
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 7145697379
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 73999252840073
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 6212002050
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 9179563562
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 15268044079
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 8952278562
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 7104844885
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 17635138008
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 76853057996294
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 13273851924
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 13828245530
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 7994629137
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 12781730390
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 13273851652
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 7948618410
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 15394187273
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 94562809294046
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 17405505478
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 2065086791
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 14777370892
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 15343645899
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 8451174579
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 18155595035
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 14582794847
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 13077370004
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 13556794361
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 12386378844
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 13580351149
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 9563784745
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 7216849215
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 13816054573
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 95193033436930
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 17634786530
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 8698794956
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 14159634300
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 15419160878
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 15419184682
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 14960668916
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 1269254614
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 1383867638
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 15264805172
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 17635993805
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 8952323069
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 8952274388
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 15816046590
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 8944375071
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 15816037556
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 12402851670
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 7145697379
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 9841273658
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 397458963
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 389222402
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 17635427457
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 119784156810130
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 8581764815
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 18122025120
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 14447188478
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 7216855914
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 2065087237
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 12945767865
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 334493095
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 14017129441
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 7096972007
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 8952292685
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 8952321410
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 8944378436
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 10335420522
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 9533204713
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 11037468570
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 15419161283
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 8952410722
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 243331916
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 8952270157
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 14856261106
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 12402861232
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 14721382247
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 6337277439
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 15268124753
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 243664672
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 6700009083
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 12852915048
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 6897736795
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 7216848401
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 9918912100
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 116288310246844
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 9563819936
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 249902641
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 10789587520
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 129066524518775
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 15268128498
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 107759572530254
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 13280146664
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 280271984
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 15268226631
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 242223105
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 89763422289713
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 6337281108
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 16129837741
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 15448668775
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 6031265978
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 4813316821
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 16950405806
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 10967049283
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 9922864240
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 12626820807
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 128948025446779
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 8292854478
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 17671379919
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 626588936
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 134123186252190
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 97336637983665
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 18252909156
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 8610473870
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 12681311322
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 91944468536305
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 18446116513
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 7216847958
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 6893847210
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 125485406249210
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 12622910157
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 6201773939
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 7261161576
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 256038163
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 867619398
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 17145866801
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 7216848493
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 13318056684
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 14735002879
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 1079347435
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 12547888947
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 136036627143435
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 125523015121474
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 17227324693
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 8599882518
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 12362734091
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 14052938411
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 10213978205
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 7216854783
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 17635005402
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 17635058082
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 13520102559
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 13510176991
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 10439119562
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 11200374925
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 7145698111
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 12591789267
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 11755027734
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 6603835352
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 101316325094869
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 106835138892794
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 9841282948
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 253188732
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 8189653993
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 12362732821
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 12402855052
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 12622911838
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 15022273655
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 3222616470
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 11724119559
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 17426601269
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 18333565511
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 16510170322
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 18921681533
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 16510180240
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 17278805287
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 18333559507
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 9432100638
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 15419161584
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 18333557885
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 6479321476
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 11724444882
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 12622908605
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 17401265236
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 18333573704
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 17401278494
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 17426600101
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 17426569877
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 12622921572
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 17278805871
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 18333562947
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 75684284598376
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 18524749520
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 18511876754
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 71064277488085
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 12362724900
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 139992348913802
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 18333567502
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 17401277349
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 17401276267
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 13861205683
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 12469099344
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 7216848586
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 17401279565
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 14043612483
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 14425197841
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 12622916288
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 18981921256
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 18333556718
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 17401271931
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 78216658443553
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 16510173329
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 7216853770
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 12622920397
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 12856058366
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 11560341824
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 7244584563
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 18333569095
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 18333554830
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 12622913348
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 13477491866
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 12622918721
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 17401270878
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 18921681721
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 13030806457
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 6749866161
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 12622914823
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 18511652417
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 18333561085
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 16924450474
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 12622922991
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 13318061510
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 18921716806
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 82081182694901
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 15419165429
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 92540430879964
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 106048361727685
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 13410128984
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 15268224750
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 16879806460
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 14859512025
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 18446116015
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 11037288610
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 12189101933
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 8952312592
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 1084987256
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 3222616800
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 8944132974
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 9541054556
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 16608498288
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 15303268480
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 16879800718
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 9563725311
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 12622924065
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 17635301675
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 10967050054
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 17635311371
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 17634951817
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 17635302684
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 139459678523921
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 13249421575
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 133977004030873
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 18450717315
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 515986879
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 1512913149
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 17635294295
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 15938804007
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 13271935089
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 12608438112
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 17635304103
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 17635317689
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 16896822643
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 6318050703
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 10967010643
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 74097430851157
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 6672981559
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 17850331753
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 603193846
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 17635312578
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 18453178759
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 17635309731
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 13273852131
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 1861106267
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 11724448121
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 121116689038631
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 17635315140
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 516660287
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 15092323853
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 17635322146
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 14844270653
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 17635299550
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 96084176893980
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 17635320860
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 17635297585
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 17635295880
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 1084962479
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 9533204568
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 11724440407
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 8952318629
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 16400268714
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 11684595935
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 11684448386
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 11684609050
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 87544797645744
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 11684646827
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 11679201516
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 11684635658
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 11684640595
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 11684617515
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 11684619942
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 11679214056
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 11679183285
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 11679206628
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 102784593690750
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 7250560778
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 9632169485
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 15057260605
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 7587238412
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 42427179
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 13405484559
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 87992137693905
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 135806867748957
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 11684639832
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 82133430923096
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 11684636719
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 11684618344
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 14197923174
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 11684642573
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 104290534027605
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 11679202707
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 242837894
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 14197924963
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 9063820505
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 11596446619
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 11679208036
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 87446280016935
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 110651390994810
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 106213945936622
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 16924513013
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 11679205312
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 248764835
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 129936988720426
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 11684648528
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 15383077623
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 11684580469
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 84033593667333
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 11684634221
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 16924949577
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 124638370947165
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 95347688912601
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 11679178526
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 243660364
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 5320460025
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 10365553156
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 71844944483584
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 7130084926
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 6127835958
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 138483942412135
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 6865222957
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 15419186633
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 17634870418
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 16004765449
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 6730324681
	},
	{
		Type = "Debris",
		FlipbookType = 1,
		TextureId = 15004585172
	}
}
