return {
	{
		Type = "Fog",
		FlipbookType = 8,
		TextureId = 10768419925
	},
	{
		Type = "Fog",
		FlipbookType = 8,
		TextureId = 11964380207
	},
	{
		Type = "Fog",
		FlipbookType = 8,
		TextureId = 10762285217
	},
	{
		Type = "Fog",
		FlipbookType = 8,
		TextureId = 17332831347
	},
	{
		Type = "Fog",
		FlipbookType = 8,
		TextureId = 10546157992
	},
	{
		Type = "Fog",
		FlipbookType = 8,
		TextureId = 17332847873
	},
	{
		Type = "Fog",
		FlipbookType = 8,
		TextureId = 10768400687
	},
	{
		Type = "Fog",
		FlipbookType = 8,
		TextureId = 17332832778
	},
	{
		Type = "Fog",
		FlipbookType = 8,
		TextureId = 14276929431
	},
	{
		Type = "Fog",
		FlipbookType = 8,
		TextureId = 10762320182
	},
	{
		Type = "Fog",
		FlipbookType = 8,
		TextureId = 129394537354054
	},
	{
		Type = "Fog",
		FlipbookType = 8,
		TextureId = 12878027420
	},
	{
		Type = "Fog",
		FlipbookType = 8,
		TextureId = 16924371519
	},
	{
		Type = "Fog",
		FlipbookType = 8,
		TextureId = 13967623404
	},
	{
		Type = "Fog",
		FlipbookType = 8,
		TextureId = 14545641289
	},
	{
		Type = "Fog",
		FlipbookType = 8,
		TextureId = 10768424377
	},
	{
		Type = "Fog",
		FlipbookType = 8,
		TextureId = 12656891791
	},
	{
		Type = "Fog",
		FlipbookType = 8,
		TextureId = 18455273735
	},
	{
		Type = "Fog",
		FlipbookType = 8,
		TextureId = 73401626133942
	},
	{
		Type = "Fog",
		FlipbookType = 8,
		TextureId = 11941047152
	},
	{
		Type = "Fog",
		FlipbookType = 8,
		TextureId = 12683695494
	},
	{
		Type = "Fog",
		FlipbookType = 8,
		TextureId = 14066311352
	},
	{
		Type = "Fog",
		FlipbookType = 8,
		TextureId = 11458438415
	},
	{
		Type = "Fog",
		FlipbookType = 8,
		TextureId = 11446801985
	},
	{
		Type = "Fog",
		FlipbookType = 8,
		TextureId = 11447021694
	},
	{
		Type = "Fog",
		FlipbookType = 8,
		TextureId = 12401154143
	},
	{
		Type = "Fog",
		FlipbookType = 8,
		TextureId = 14953437740
	},
	{
		Type = "Fog",
		FlipbookType = 8,
		TextureId = 13131157579
	},
	{
		Type = "Fog",
		FlipbookType = 8,
		TextureId = 96540548770170
	},
	{
		Type = "Fog",
		FlipbookType = 8,
		TextureId = 12780365055
	},
	{
		Type = "Fog",
		FlipbookType = 8,
		TextureId = 92517106717850
	},
	{
		Type = "Fog",
		FlipbookType = 8,
		TextureId = 136111736121725
	},
	{
		Type = "Fog",
		FlipbookType = 8,
		TextureId = 135611124886147
	},
	{
		Type = "Fog",
		FlipbookType = 8,
		TextureId = 11799788138
	},
	{
		Type = "Fog",
		FlipbookType = 8,
		TextureId = 83086555210331
	},
	{
		Type = "Fog",
		FlipbookType = 8,
		TextureId = 96772682616550
	},
	{
		Type = "Fog",
		FlipbookType = 8,
		TextureId = 13368444414
	},
	{
		Type = "Fog",
		FlipbookType = 8,
		TextureId = 9173527444
	},
	{
		Type = "Fog",
		FlipbookType = 8,
		TextureId = 11799607237
	},
	{
		Type = "Fog",
		FlipbookType = 8,
		TextureId = 16503748507
	},
	{
		Type = "Fog",
		FlipbookType = 8,
		TextureId = 13712000835
	},
	{
		Type = "Fog",
		FlipbookType = 8,
		TextureId = 11338531964
	},
	{
		Type = "Fog",
		FlipbookType = 8,
		TextureId = 82103606978024
	},
	{
		Type = "Fog",
		FlipbookType = 8,
		TextureId = 17510992903
	},
	{
		Type = "Fog",
		FlipbookType = 8,
		TextureId = 12306745644
	},
	{
		Type = "Fog",
		FlipbookType = 8,
		TextureId = 13335693944
	},
	{
		Type = "Fog",
		FlipbookType = 8,
		TextureId = 11568149153
	},
	{
		Type = "Fog",
		FlipbookType = 8,
		TextureId = 14050551379
	},
	{
		Type = "Fog",
		FlipbookType = 8,
		TextureId = 12865656309
	},
	{
		Type = "Fog",
		FlipbookType = 8,
		TextureId = 105131408419595
	},
	{
		Type = "Fog",
		FlipbookType = 8,
		TextureId = 90758860623521
	},
	{
		Type = "Fog",
		FlipbookType = 8,
		TextureId = 16511222025
	},
	{
		Type = "Fog",
		FlipbookType = 8,
		TextureId = 14979969015
	},
	{
		Type = "Fog",
		FlipbookType = 8,
		TextureId = 92045720541673
	},
	{
		Type = "Fog",
		FlipbookType = 8,
		TextureId = 14727016281
	},
	{
		Type = "Fog",
		FlipbookType = 8,
		TextureId = 12441202218
	},
	{
		Type = "Fog",
		FlipbookType = 8,
		TextureId = 14151918862
	},
	{
		Type = "Fog",
		FlipbookType = 8,
		TextureId = 16511790647
	},
	{
		Type = "Fog",
		FlipbookType = 8,
		TextureId = 16512020778
	},
	{
		Type = "Fog",
		FlipbookType = 8,
		TextureId = 16511930894
	},
	{
		Type = "Fog",
		FlipbookType = 8,
		TextureId = 83784868925844
	},
	{
		Type = "Fog",
		FlipbookType = 8,
		TextureId = 12810256703
	},
	{
		Type = "Fog",
		FlipbookType = 8,
		TextureId = 11627083142
	},
	{
		Type = "Fog",
		FlipbookType = 8,
		TextureId = 15675258695
	},
	{
		Type = "Fog",
		FlipbookType = 8,
		TextureId = 14590103902
	},
	{
		Type = "Fog",
		FlipbookType = 8,
		TextureId = 13974146438
	},
	{
		Type = "Fog",
		FlipbookType = 8,
		TextureId = 15222191191
	},
	{
		Type = "Fog",
		FlipbookType = 8,
		TextureId = 12656890801
	},
	{
		Type = "Fog",
		FlipbookType = 8,
		TextureId = 16511598488
	},
	{
		Type = "Fog",
		FlipbookType = 8,
		TextureId = 8073306083
	},
	{
		Type = "Fog",
		FlipbookType = 8,
		TextureId = 11381555015
	},
	{
		Type = "Fog",
		FlipbookType = 8,
		TextureId = 14833552906
	},
	{
		Type = "Fog",
		FlipbookType = 8,
		TextureId = 11355872735
	},
	{
		Type = "Fog",
		FlipbookType = 8,
		TextureId = 12656891076
	},
	{
		Type = "Fog",
		FlipbookType = 8,
		TextureId = 11828552375
	},
	{
		Type = "Fog",
		FlipbookType = 8,
		TextureId = 14050576113
	},
	{
		Type = "Fog",
		FlipbookType = 8,
		TextureId = 15009885079
	},
	{
		Type = "Fog",
		FlipbookType = 8,
		TextureId = 12656890347
	},
	{
		Type = "Fog",
		FlipbookType = 8,
		TextureId = 13712003438
	},
	{
		Type = "Fog",
		FlipbookType = 8,
		TextureId = 16503738541
	},
	{
		Type = "Fog",
		FlipbookType = 8,
		TextureId = 16511373646
	},
	{
		Type = "Fog",
		FlipbookType = 8,
		TextureId = 13712003050
	},
	{
		Type = "Fog",
		FlipbookType = 8,
		TextureId = 16503725723
	},
	{
		Type = "Fog",
		FlipbookType = 8,
		TextureId = 15677400106
	},
	{
		Type = "Fog",
		FlipbookType = 8,
		TextureId = 132537238667080
	},
	{
		Type = "Fog",
		FlipbookType = 8,
		TextureId = 127860061030425
	},
	{
		Type = "Fog",
		FlipbookType = 8,
		TextureId = 15675210127
	},
	{
		Type = "Fog",
		FlipbookType = 8,
		TextureId = 9470659899
	},
	{
		Type = "Fog",
		FlipbookType = 8,
		TextureId = 14645775583
	},
	{
		Type = "Fog",
		FlipbookType = 8,
		TextureId = 14263168584
	},
	{
		Type = "Fog",
		FlipbookType = 8,
		TextureId = 16511681922
	},
	{
		Type = "Fog",
		FlipbookType = 8,
		TextureId = 11355816590
	},
	{
		Type = "Fog",
		FlipbookType = 8,
		TextureId = 16503766653
	},
	{
		Type = "Fog",
		FlipbookType = 8,
		TextureId = 13026594575
	},
	{
		Type = "Fog",
		FlipbookType = 8,
		TextureId = 15348984746
	},
	{
		Type = "Fog",
		FlipbookType = 8,
		TextureId = 18451844545
	},
	{
		Type = "Fog",
		FlipbookType = 8,
		TextureId = 11381560992
	},
	{
		Type = "Fog",
		FlipbookType = 8,
		TextureId = 12830011666
	},
	{
		Type = "Fog",
		FlipbookType = 8,
		TextureId = 12779603482
	},
	{
		Type = "Fog",
		FlipbookType = 8,
		TextureId = 11381553025
	},
	{
		Type = "Fog",
		FlipbookType = 8,
		TextureId = 11627077002
	},
	{
		Type = "Fog",
		FlipbookType = 8,
		TextureId = 16511637504
	},
	{
		Type = "Fog",
		FlipbookType = 8,
		TextureId = 10034873151
	},
	{
		Type = "Fog",
		FlipbookType = 8,
		TextureId = 16511720979
	},
	{
		Type = "Fog",
		FlipbookType = 8,
		TextureId = 15686854301
	},
	{
		Type = "Fog",
		FlipbookType = 8,
		TextureId = 11355845008
	},
	{
		Type = "Fog",
		FlipbookType = 8,
		TextureId = 16503783638
	},
	{
		Type = "Fog",
		FlipbookType = 8,
		TextureId = 11381557354
	},
	{
		Type = "Fog",
		FlipbookType = 8,
		TextureId = 16503813045
	},
	{
		Type = "Fog",
		FlipbookType = 8,
		TextureId = 16503468487
	},
	{
		Type = "Fog",
		FlipbookType = 8,
		TextureId = 88690400621954
	},
	{
		Type = "Fog",
		FlipbookType = 8,
		TextureId = 13843143422
	},
	{
		Type = "Fog",
		FlipbookType = 8,
		TextureId = 12656879896
	},
	{
		Type = "Fog",
		FlipbookType = 8,
		TextureId = 12656890572
	},
	{
		Type = "Fog",
		FlipbookType = 8,
		TextureId = 14186189742
	},
	{
		Type = "Fog",
		FlipbookType = 8,
		TextureId = 16511331302
	},
	{
		Type = "Fog",
		FlipbookType = 8,
		TextureId = 12656891465
	},
	{
		Type = "Fog",
		FlipbookType = 8,
		TextureId = 12656877787
	},
	{
		Type = "Fog",
		FlipbookType = 4,
		TextureId = 11917388916
	},
	{
		Type = "Fog",
		FlipbookType = 4,
		TextureId = 134005434290423
	},
	{
		Type = "Fog",
		FlipbookType = 4,
		TextureId = 140471746213044
	},
	{
		Type = "Fog",
		FlipbookType = 4,
		TextureId = 132473034854893
	},
	{
		Type = "Fog",
		FlipbookType = 4,
		TextureId = 13826565206
	},
	{
		Type = "Fog",
		FlipbookType = 4,
		TextureId = 138270984714302
	},
	{
		Type = "Fog",
		FlipbookType = 4,
		TextureId = 119285901217815
	},
	{
		Type = "Fog",
		FlipbookType = 4,
		TextureId = 13580372792
	},
	{
		Type = "Fog",
		FlipbookType = 4,
		TextureId = 14393243408
	},
	{
		Type = "Fog",
		FlipbookType = 4,
		TextureId = 92739826225814
	},
	{
		Type = "Fog",
		FlipbookType = 4,
		TextureId = 17511044995
	},
	{
		Type = "Fog",
		FlipbookType = 4,
		TextureId = 126057477044712
	},
	{
		Type = "Fog",
		FlipbookType = 4,
		TextureId = 13928180948
	},
	{
		Type = "Fog",
		FlipbookType = 4,
		TextureId = 11597664950
	},
	{
		Type = "Fog",
		FlipbookType = 4,
		TextureId = 11842590711
	},
	{
		Type = "Fog",
		FlipbookType = 4,
		TextureId = 104888060261813
	},
	{
		Type = "Fog",
		FlipbookType = 4,
		TextureId = 16924697121
	},
	{
		Type = "Fog",
		FlipbookType = 4,
		TextureId = 14442131728
	},
	{
		Type = "Fog",
		FlipbookType = 4,
		TextureId = 102472052965646
	},
	{
		Type = "Fog",
		FlipbookType = 4,
		TextureId = 15398191874
	},
	{
		Type = "Fog",
		FlipbookType = 4,
		TextureId = 16867389591
	},
	{
		Type = "Fog",
		FlipbookType = 4,
		TextureId = 89353525350224
	},
	{
		Type = "Fog",
		FlipbookType = 4,
		TextureId = 121001088865254
	},
	{
		Type = "Fog",
		FlipbookType = 4,
		TextureId = 15441275183
	},
	{
		Type = "Fog",
		FlipbookType = 4,
		TextureId = 13743483729
	},
	{
		Type = "Fog",
		FlipbookType = 4,
		TextureId = 12110213243
	},
	{
		Type = "Fog",
		FlipbookType = 4,
		TextureId = 15072761142
	},
	{
		Type = "Fog",
		FlipbookType = 4,
		TextureId = 13828988163
	},
	{
		Type = "Fog",
		FlipbookType = 4,
		TextureId = 15481334255
	},
	{
		Type = "Fog",
		FlipbookType = 4,
		TextureId = 123675807271031
	},
	{
		Type = "Fog",
		FlipbookType = 4,
		TextureId = 12131483712
	},
	{
		Type = "Fog",
		FlipbookType = 4,
		TextureId = 17517657351
	},
	{
		Type = "Fog",
		FlipbookType = 4,
		TextureId = 12800353201
	},
	{
		Type = "Fog",
		FlipbookType = 4,
		TextureId = 13367803563
	},
	{
		Type = "Fog",
		FlipbookType = 4,
		TextureId = 18326864825
	},
	{
		Type = "Fog",
		FlipbookType = 4,
		TextureId = 106803572618024
	},
	{
		Type = "Fog",
		FlipbookType = 4,
		TextureId = 73401369007395
	},
	{
		Type = "Fog",
		FlipbookType = 4,
		TextureId = 70989844984628
	},
	{
		Type = "Fog",
		FlipbookType = 4,
		TextureId = 95932563257720
	},
	{
		Type = "Fog",
		FlipbookType = 4,
		TextureId = 13989966715
	},
	{
		Type = "Fog",
		FlipbookType = 4,
		TextureId = 12506004739
	},
	{
		Type = "Fog",
		FlipbookType = 4,
		TextureId = 13745021655
	},
	{
		Type = "Fog",
		FlipbookType = 4,
		TextureId = 16924666767
	},
	{
		Type = "Fog",
		FlipbookType = 4,
		TextureId = 17510999750
	},
	{
		Type = "Fog",
		FlipbookType = 4,
		TextureId = 13726311040
	},
	{
		Type = "Fog",
		FlipbookType = 4,
		TextureId = 87542617578573
	},
	{
		Type = "Fog",
		FlipbookType = 4,
		TextureId = 94513258966357
	},
	{
		Type = "Fog",
		FlipbookType = 4,
		TextureId = 13739512481
	},
	{
		Type = "Fog",
		FlipbookType = 4,
		TextureId = 11844017484
	},
	{
		Type = "Fog",
		FlipbookType = 4,
		TextureId = 13717823765
	},
	{
		Type = "Fog",
		FlipbookType = 4,
		TextureId = 16924943483
	},
	{
		Type = "Fog",
		FlipbookType = 4,
		TextureId = 13414392494
	},
	{
		Type = "Fog",
		FlipbookType = 4,
		TextureId = 15433989948
	},
	{
		Type = "Fog",
		FlipbookType = 4,
		TextureId = 12237413962
	},
	{
		Type = "Fog",
		FlipbookType = 4,
		TextureId = 134788710166485
	},
	{
		Type = "Fog",
		FlipbookType = 4,
		TextureId = 16857504782
	},
	{
		Type = "Fog",
		FlipbookType = 4,
		TextureId = 132125856027392
	},
	{
		Type = "Fog",
		FlipbookType = 4,
		TextureId = 126178873329014
	},
	{
		Type = "Fog",
		FlipbookType = 4,
		TextureId = 18456244650
	},
	{
		Type = "Fog",
		FlipbookType = 4,
		TextureId = 76204681346241
	},
	{
		Type = "Fog",
		FlipbookType = 4,
		TextureId = 137012881677881
	},
	{
		Type = "Fog",
		FlipbookType = 4,
		TextureId = 139795450630850
	},
	{
		Type = "Fog",
		FlipbookType = 4,
		TextureId = 93425112299725
	},
	{
		Type = "Fog",
		FlipbookType = 4,
		TextureId = 18369727963
	},
	{
		Type = "Fog",
		FlipbookType = 4,
		TextureId = 12123878312
	},
	{
		Type = "Fog",
		FlipbookType = 4,
		TextureId = 13505055012
	},
	{
		Type = "Fog",
		FlipbookType = 4,
		TextureId = 11866632577
	},
	{
		Type = "Fog",
		FlipbookType = 4,
		TextureId = 13455668887
	},
	{
		Type = "Fog",
		FlipbookType = 4,
		TextureId = 18761487473
	},
	{
		Type = "Fog",
		FlipbookType = 4,
		TextureId = 9358399742
	},
	{
		Type = "Fog",
		FlipbookType = 4,
		TextureId = 13468353904
	},
	{
		Type = "Fog",
		FlipbookType = 4,
		TextureId = 16509877465
	},
	{
		Type = "Fog",
		FlipbookType = 4,
		TextureId = 9380861547
	},
	{
		Type = "Fog",
		FlipbookType = 4,
		TextureId = 94034986994196
	},
	{
		Type = "Fog",
		FlipbookType = 4,
		TextureId = 11871320339
	},
	{
		Type = "Fog",
		FlipbookType = 4,
		TextureId = 132218055971337
	},
	{
		Type = "Fog",
		FlipbookType = 4,
		TextureId = 113206708550622
	},
	{
		Type = "Fog",
		FlipbookType = 4,
		TextureId = 138628211703034
	},
	{
		Type = "Fog",
		FlipbookType = 4,
		TextureId = 13346862770
	},
	{
		Type = "Fog",
		FlipbookType = 4,
		TextureId = 99478975615194
	},
	{
		Type = "Fog",
		FlipbookType = 4,
		TextureId = 16503588946
	},
	{
		Type = "Fog",
		FlipbookType = 4,
		TextureId = 14601007537
	},
	{
		Type = "Fog",
		FlipbookType = 4,
		TextureId = 16015157826
	},
	{
		Type = "Fog",
		FlipbookType = 4,
		TextureId = 16708557658
	},
	{
		Type = "Fog",
		FlipbookType = 4,
		TextureId = 11846336638
	},
	{
		Type = "Fog",
		FlipbookType = 4,
		TextureId = 11841348746
	},
	{
		Type = "Fog",
		FlipbookType = 4,
		TextureId = 102145598777345
	},
	{
		Type = "Fog",
		FlipbookType = 4,
		TextureId = 11858203067
	},
	{
		Type = "Fog",
		FlipbookType = 4,
		TextureId = 14560297845
	},
	{
		Type = "Fog",
		FlipbookType = 4,
		TextureId = 137168315504594
	},
	{
		Type = "Fog",
		FlipbookType = 4,
		TextureId = 14006773822
	},
	{
		Type = "Fog",
		FlipbookType = 4,
		TextureId = 16651298188
	},
	{
		Type = "Fog",
		FlipbookType = 4,
		TextureId = 16860267787
	},
	{
		Type = "Fog",
		FlipbookType = 4,
		TextureId = 12807576645
	},
	{
		Type = "Fog",
		FlipbookType = 4,
		TextureId = 71725986475684
	},
	{
		Type = "Fog",
		FlipbookType = 4,
		TextureId = 13826100764
	},
	{
		Type = "Fog",
		FlipbookType = 4,
		TextureId = 109177800801971
	},
	{
		Type = "Fog",
		FlipbookType = 4,
		TextureId = 14526168571
	},
	{
		Type = "Fog",
		FlipbookType = 4,
		TextureId = 11163755167
	},
	{
		Type = "Fog",
		FlipbookType = 4,
		TextureId = 12360035207
	},
	{
		Type = "Fog",
		FlipbookType = 4,
		TextureId = 84810509846193
	},
	{
		Type = "Fog",
		FlipbookType = 4,
		TextureId = 12437246241
	},
	{
		Type = "Fog",
		FlipbookType = 4,
		TextureId = 11854297993
	},
	{
		Type = "Fog",
		FlipbookType = 4,
		TextureId = 11989899750
	},
	{
		Type = "Fog",
		FlipbookType = 4,
		TextureId = 99398524036719
	},
	{
		Type = "Fog",
		FlipbookType = 4,
		TextureId = 11381706270
	},
	{
		Type = "Fog",
		FlipbookType = 4,
		TextureId = 16018044176
	},
	{
		Type = "Fog",
		FlipbookType = 4,
		TextureId = 16924888769
	},
	{
		Type = "Fog",
		FlipbookType = 4,
		TextureId = 16850891267
	},
	{
		Type = "Fog",
		FlipbookType = 4,
		TextureId = 118502250537213
	},
	{
		Type = "Fog",
		FlipbookType = 4,
		TextureId = 18761902078
	},
	{
		Type = "Fog",
		FlipbookType = 4,
		TextureId = 13261064383
	},
	{
		Type = "Fog",
		FlipbookType = 4,
		TextureId = 13992214801
	},
	{
		Type = "Fog",
		FlipbookType = 4,
		TextureId = 76562233925062
	},
	{
		Type = "Fog",
		FlipbookType = 4,
		TextureId = 94505125106448
	},
	{
		Type = "Fog",
		FlipbookType = 4,
		TextureId = 13811889171
	},
	{
		Type = "Fog",
		FlipbookType = 4,
		TextureId = 14394427356
	},
	{
		Type = "Fog",
		FlipbookType = 4,
		TextureId = 13013256540
	},
	{
		Type = "Fog",
		FlipbookType = 4,
		TextureId = 89779528189516
	},
	{
		Type = "Fog",
		FlipbookType = 4,
		TextureId = 11853980698
	},
	{
		Type = "Fog",
		FlipbookType = 4,
		TextureId = 14641036736
	},
	{
		Type = "Fog",
		FlipbookType = 4,
		TextureId = 16997104240
	},
	{
		Type = "Fog",
		FlipbookType = 4,
		TextureId = 120399667857560
	},
	{
		Type = "Fog",
		FlipbookType = 4,
		TextureId = 16924362907
	},
	{
		Type = "Fog",
		FlipbookType = 4,
		TextureId = 110549281481684
	},
	{
		Type = "Fog",
		FlipbookType = 4,
		TextureId = 12350056117
	},
	{
		Type = "Fog",
		FlipbookType = 4,
		TextureId = 129749938018855
	},
	{
		Type = "Fog",
		FlipbookType = 4,
		TextureId = 13820471965
	},
	{
		Type = "Fog",
		FlipbookType = 4,
		TextureId = 11163763158
	},
	{
		Type = "Fog",
		FlipbookType = 4,
		TextureId = 17116649003
	},
	{
		Type = "Fog",
		FlipbookType = 4,
		TextureId = 11822996479
	},
	{
		Type = "Fog",
		FlipbookType = 4,
		TextureId = 131880846582449
	},
	{
		Type = "Fog",
		FlipbookType = 4,
		TextureId = 15013979783
	},
	{
		Type = "Fog",
		FlipbookType = 4,
		TextureId = 9754671071
	},
	{
		Type = "Fog",
		FlipbookType = 4,
		TextureId = 15562554136
	},
	{
		Type = "Fog",
		FlipbookType = 4,
		TextureId = 16509852217
	},
	{
		Type = "Fog",
		FlipbookType = 4,
		TextureId = 86084100736490
	},
	{
		Type = "Fog",
		FlipbookType = 4,
		TextureId = 14200879082
	},
	{
		Type = "Fog",
		FlipbookType = 4,
		TextureId = 16878191468
	},
	{
		Type = "Fog",
		FlipbookType = 4,
		TextureId = 16867490141
	},
	{
		Type = "Fog",
		FlipbookType = 4,
		TextureId = 14279261803
	},
	{
		Type = "Fog",
		FlipbookType = 4,
		TextureId = 11846119288
	},
	{
		Type = "Fog",
		FlipbookType = 4,
		TextureId = 14830736372
	},
	{
		Type = "Fog",
		FlipbookType = 4,
		TextureId = 15083750522
	},
	{
		Type = "Fog",
		FlipbookType = 4,
		TextureId = 16860461660
	},
	{
		Type = "Fog",
		FlipbookType = 4,
		TextureId = 14061881951
	},
	{
		Type = "Fog",
		FlipbookType = 4,
		TextureId = 13370270611
	},
	{
		Type = "Fog",
		FlipbookType = 4,
		TextureId = 14476165199
	},
	{
		Type = "Fog",
		FlipbookType = 4,
		TextureId = 15415212938
	},
	{
		Type = "Fog",
		FlipbookType = 4,
		TextureId = 14163162698
	},
	{
		Type = "Fog",
		FlipbookType = 4,
		TextureId = 133171799071569
	},
	{
		Type = "Fog",
		FlipbookType = 4,
		TextureId = 17727455731
	},
	{
		Type = "Fog",
		FlipbookType = 4,
		TextureId = 117571359644909
	},
	{
		Type = "Fog",
		FlipbookType = 4,
		TextureId = 78536095614807
	},
	{
		Type = "Fog",
		FlipbookType = 4,
		TextureId = 14919880888
	},
	{
		Type = "Fog",
		FlipbookType = 4,
		TextureId = 15011471927
	},
	{
		Type = "Fog",
		FlipbookType = 4,
		TextureId = 13934610516
	},
	{
		Type = "Fog",
		FlipbookType = 4,
		TextureId = 117899608714187
	},
	{
		Type = "Fog",
		FlipbookType = 4,
		TextureId = 16172858603
	},
	{
		Type = "Fog",
		FlipbookType = 4,
		TextureId = 13820562548
	},
	{
		Type = "Fog",
		FlipbookType = 4,
		TextureId = 11826642105
	},
	{
		Type = "Fog",
		FlipbookType = 4,
		TextureId = 13727078625
	},
	{
		Type = "Fog",
		FlipbookType = 4,
		TextureId = 85177047823763
	},
	{
		Type = "Fog",
		FlipbookType = 4,
		TextureId = 15441247020
	},
	{
		Type = "Fog",
		FlipbookType = 4,
		TextureId = 14842257638
	},
	{
		Type = "Fog",
		FlipbookType = 4,
		TextureId = 127602127470983
	},
	{
		Type = "Fog",
		FlipbookType = 4,
		TextureId = 13726321388
	},
	{
		Type = "Fog",
		FlipbookType = 4,
		TextureId = 16924755732
	},
	{
		Type = "Fog",
		FlipbookType = 4,
		TextureId = 87694680685820
	},
	{
		Type = "Fog",
		FlipbookType = 4,
		TextureId = 14451121834
	},
	{
		Type = "Fog",
		FlipbookType = 4,
		TextureId = 134254043650523
	},
	{
		Type = "Fog",
		FlipbookType = 4,
		TextureId = 16924746286
	},
	{
		Type = "Fog",
		FlipbookType = 4,
		TextureId = 137375810778410
	},
	{
		Type = "Fog",
		FlipbookType = 4,
		TextureId = 11826696782
	},
	{
		Type = "Fog",
		FlipbookType = 4,
		TextureId = 87418254231660
	},
	{
		Type = "Fog",
		FlipbookType = 4,
		TextureId = 137087333353962
	},
	{
		Type = "Fog",
		FlipbookType = 4,
		TextureId = 13718060871
	},
	{
		Type = "Fog",
		FlipbookType = 4,
		TextureId = 94224152098836
	},
	{
		Type = "Fog",
		FlipbookType = 4,
		TextureId = 13927257008
	},
	{
		Type = "Fog",
		FlipbookType = 4,
		TextureId = 11827778171
	},
	{
		Type = "Fog",
		FlipbookType = 4,
		TextureId = 15483343964
	},
	{
		Type = "Fog",
		FlipbookType = 4,
		TextureId = 14039691837
	},
	{
		Type = "Fog",
		FlipbookType = 4,
		TextureId = 9358765944
	},
	{
		Type = "Fog",
		FlipbookType = 4,
		TextureId = 105226106571101
	},
	{
		Type = "Fog",
		FlipbookType = 4,
		TextureId = 103320631160808
	},
	{
		Type = "Fog",
		FlipbookType = 4,
		TextureId = 17000893814
	},
	{
		Type = "Fog",
		FlipbookType = 4,
		TextureId = 16877892005
	},
	{
		Type = "Fog",
		FlipbookType = 4,
		TextureId = 131102628942422
	},
	{
		Type = "Fog",
		FlipbookType = 4,
		TextureId = 15107683952
	},
	{
		Type = "Fog",
		FlipbookType = 4,
		TextureId = 13180760354
	},
	{
		Type = "Fog",
		FlipbookType = 4,
		TextureId = 14389391340
	},
	{
		Type = "Fog",
		FlipbookType = 4,
		TextureId = 16924352957
	},
	{
		Type = "Fog",
		FlipbookType = 4,
		TextureId = 15051270398
	},
	{
		Type = "Fog",
		FlipbookType = 4,
		TextureId = 13052525496
	},
	{
		Type = "Fog",
		FlipbookType = 4,
		TextureId = 12360893247
	},
	{
		Type = "Fog",
		FlipbookType = 4,
		TextureId = 120154460257489
	},
	{
		Type = "Fog",
		FlipbookType = 4,
		TextureId = 16879534356
	},
	{
		Type = "Fog",
		FlipbookType = 4,
		TextureId = 17703378809
	},
	{
		Type = "Fog",
		FlipbookType = 4,
		TextureId = 16924766431
	},
	{
		Type = "Fog",
		FlipbookType = 4,
		TextureId = 16503876723
	},
	{
		Type = "Fog",
		FlipbookType = 4,
		TextureId = 13765238618
	},
	{
		Type = "Fog",
		FlipbookType = 4,
		TextureId = 16867444334
	},
	{
		Type = "Fog",
		FlipbookType = 4,
		TextureId = 11867465395
	},
	{
		Type = "Fog",
		FlipbookType = 4,
		TextureId = 13486412308
	},
	{
		Type = "Fog",
		FlipbookType = 4,
		TextureId = 12360893247
	},
	{
		Type = "Fog",
		FlipbookType = 4,
		TextureId = 13469952619
	},
	{
		Type = "Fog",
		FlipbookType = 4,
		TextureId = 16334792296
	},
	{
		Type = "Fog",
		FlipbookType = 4,
		TextureId = 13935219969
	},
	{
		Type = "Fog",
		FlipbookType = 4,
		TextureId = 100900157130245
	},
	{
		Type = "Fog",
		FlipbookType = 4,
		TextureId = 131430226944103
	},
	{
		Type = "Fog",
		FlipbookType = 4,
		TextureId = 15222190200
	},
	{
		Type = "Fog",
		FlipbookType = 4,
		TextureId = 95513716693179
	},
	{
		Type = "Fog",
		FlipbookType = 4,
		TextureId = 16771440490
	},
	{
		Type = "Fog",
		FlipbookType = 2,
		TextureId = 16924518099
	},
	{
		Type = "Fog",
		FlipbookType = 2,
		TextureId = 13935107767
	},
	{
		Type = "Fog",
		FlipbookType = 2,
		TextureId = 12221939491
	},
	{
		Type = "Fog",
		FlipbookType = 2,
		TextureId = 14050533905
	},
	{
		Type = "Fog",
		FlipbookType = 2,
		TextureId = 12221929606
	},
	{
		Type = "Fog",
		FlipbookType = 2,
		TextureId = 135279586943950
	},
	{
		Type = "Fog",
		FlipbookType = 2,
		TextureId = 17612127081
	},
	{
		Type = "Fog",
		FlipbookType = 2,
		TextureId = 70371037304563
	},
	{
		Type = "Fog",
		FlipbookType = 2,
		TextureId = 103895216347171
	},
	{
		Type = "Fog",
		FlipbookType = 2,
		TextureId = 14050526759
	},
	{
		Type = "Fog",
		FlipbookType = 2,
		TextureId = 14052682097
	},
	{
		Type = "Fog",
		FlipbookType = 2,
		TextureId = 9171263549
	},
	{
		Type = "Fog",
		FlipbookType = 2,
		TextureId = 12800353914
	},
	{
		Type = "Fog",
		FlipbookType = 2,
		TextureId = 83555168919553
	},
	{
		Type = "Fog",
		FlipbookType = 2,
		TextureId = 11764000644
	},
	{
		Type = "Fog",
		FlipbookType = 2,
		TextureId = 87158052323401
	},
	{
		Type = "Fog",
		FlipbookType = 2,
		TextureId = 12800351571
	},
	{
		Type = "Fog",
		FlipbookType = 2,
		TextureId = 12930785601
	},
	{
		Type = "Fog",
		FlipbookType = 2,
		TextureId = 17492126738
	},
	{
		Type = "Fog",
		FlipbookType = 2,
		TextureId = 13975873083
	}
}
