return {
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 11037284566
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 18618625614
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 15502011151
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 8944420354
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 8944422104
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 8944413317
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 11037285896
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 8952265505
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 8944418385
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 18614257863
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 18612733944
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 7216847219
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 1084966670
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 17635257304
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 17634962372
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 13772117423
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 17634875682
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 17635244226
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 17634965800
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 17635225238
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 242292288
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 17634960996
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 17634974955
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 17635221130
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 17635200513
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12362727262
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 17635208781
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12362718461
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12403189245
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12403131172
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12403110781
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12402905330
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12402928084
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12402909026
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12402907501
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12402920196
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12402923862
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12402906105
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 17426631406
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 11684643813
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 11684598669
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 11679199504
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 11684637564
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12362661645
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 17635202299
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 17635077312
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 17634794616
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 17635223113
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 17635210681
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12403077402
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12403161861
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 11684603808
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 11684605828
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 11684641167
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 11684602469
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 11684638391
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 17634957198
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 16505076059
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 17635165364
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12402870077
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 17635176429
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 17635168305
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12402926077
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 11684649126
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 17635323477
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 17634969153
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12403142931
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12403098055
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12403176165
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12402922718
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 17635173450
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 17634967943
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 17635992233
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 17635228616
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 17635977727
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 17635233169
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12403150184
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 17635205401
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 17634886331
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 17635251288
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 15824428535
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 17635324455
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 17634943647
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 7216847342
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12362700003
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12362688973
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12402908433
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12402911244
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 11684629169
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12362671392
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12362673556
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 17765068700
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 17635246383
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 17634954957
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 242949855
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 17635190987
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 17765067104
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 1053551368
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 17635306867
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12402930237
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12403159934
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 17635241615
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12362691597
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 11684632844
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12362696518
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12403078255
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 15987842404
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 17635922665
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 17635925638
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 17635250167
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 17635255659
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 15264947927
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 11684641836
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 17635153460
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12403079236
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 11684643167
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 11684646269
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12362707658
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 11684621536
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 11684623831
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12403099049
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 11684622841
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 11679211461
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12402924324
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12362687183
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12362665983
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12362684546
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12362693908
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12402926722
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12403175468
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 17635180462
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 17635192867
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12403156355
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12362706175
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12362664637
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12362658430
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12547626704
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12403151766
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 11684616485
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12362659321
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 11684619293
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12403081120
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12403080448
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12362662895
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12362685876
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 17635254286
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 17635184510
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 13271204022
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 17635308221
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12362715793
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 17635271341
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 17634960026
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 14315547017
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 17635207081
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 17635226634
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12362689688
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 15416410678
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12362695688
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12403103765
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 17635252537
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 17634973534
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 17635927489
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 17634972059
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 17635982038
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12362724228
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12402906588
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12362654779
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12402909883
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 17634966823
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 17635178534
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12362690602
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12402910563
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12362700915
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12362660306
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12402904237
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 17635970726
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 17635434310
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 17634964566
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 17635078450
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 17634953027
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 17635978946
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12362674683
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 2048097307
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12362672519
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 17635325161
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 17634956174
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 17634970255
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 5639840603
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 2065072762
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 5021159599
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 108917421397535
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 8152628560
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 10002492897
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12402921038
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12403153232
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12403160686
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 6631155345
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12403111770
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12402916099
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12403154690
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12403158002
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 11684597215
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 11684607334
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 15268083067
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 17635247924
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 6472896673
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 5234388158
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12402921742
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 11684576758
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 17838038413
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12403110071
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12403169119
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 5561954395
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 7216846971
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 11684614107
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12403072039
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 11684647694
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12403162805
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 11684610254
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12403097047
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12403174434
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 11679196837
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12402867524
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12403148228
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12403183334
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12547793489
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12403134420
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12403109404
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12403159022
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 9563790939
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12547668921
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12547652032
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12362755081
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12547876992
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 11684615113
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12547875936
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12362762318
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12547690415
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 9563795060
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12403182386
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12403185411
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12403073599
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12362706897
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12676066640
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12402917659
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12547910495
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12403101064
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12547617505
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12403071027
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 9563783593
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 17426634267
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12676007909
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 2866648598
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 241778280
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 117145102237726
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12547887476
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12362726009
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12362669248
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12547874819
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12362727886
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12403172363
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 88576623488616
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 114062332201426
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12402929507
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12402918546
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 9563793649
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12547618550
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12547736086
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 6034268012
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12547706610
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 9563932531
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 104551724222085
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 13366474252
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 9563931685
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12362739010
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12403120370
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12403075151
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 11679181411
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 14050926290
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 11684612823
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12547643265
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 17635318835
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12402925126
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12403076360
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12402927427
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12547947459
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 5171039460
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 16494997922
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12362743880
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12403166125
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 9563810958
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 9563933258
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 15264924856
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 13322042034
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 6590251003
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12547641625
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12403118750
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 9563816638
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 9563595028
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12362697198
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 9563726020
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 9563793878
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 9563724604
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12547784550
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 9563800758
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12547897123
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12403115986
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 9563796105
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12403074148
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12547738387
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12547908879
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 16510067547
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 1233066225
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12547757655
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 15264895013
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 7994629407
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12403188583
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 9563781236
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 9563941122
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 9563944066
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 6031094667
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12362758001
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12547707891
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 13027513864
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 9563795422
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 9563784467
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 9563932795
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 9563941378
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 16510018821
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 16510062597
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 16510049181
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12547675099
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12547705456
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12547929996
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12362743319
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 8214517928
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 9563588001
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 9563791878
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 9563785251
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 9563728434
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12402916748
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 16933064607
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12403121412
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12403126506
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12547739530
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12403173090
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12403102910
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12403173741
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12362739694
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12547661743
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 8898417863
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 11349514768
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 106019463649985
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12547678867
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12905962634
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12547925258
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12547881357
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12547651138
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 15814661677
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 14164260155
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12403164151
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12402868275
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12547640469
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12362740456
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12403175005
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12547952729
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 9563945564
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12402913998
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12362741277
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12547741967
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12547666345
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12435981952
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12403179421
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12547701338
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12403124367
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12402913157
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 9563594300
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 9563796583
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 18731737602
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 9563790132
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 8214519369
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12547681384
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 2065074380
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12547774692
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 14221272033
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 16510070016
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 16510121608
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12547884021
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12547644239
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12547616273
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12547649589
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 16510217701
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 16510133165
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12547657219
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 128794793203704
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12547673933
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12547667758
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12402914955
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12547862126
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12547860653
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12547893245
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12547645484
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 98044292505292
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12547915516
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12547936472
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12547632300
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12547753156
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12547842754
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12403167048
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12547725117
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12403152671
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 6654271542
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12403177657
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12403171432
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12403163501
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12547688401
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12403181647
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 9563944227
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12362770368
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12362748063
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 8214518976
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 7948615765
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12547682557
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12547620504
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 9563788818
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12547658489
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12547964699
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 6473251976
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 14279114116
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12547636131
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12547702810
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 16510114415
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 2065074172
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 17426530339
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 14968547077
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 14396673907
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 3057073083
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 16510116852
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12547763659
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 1084952073
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 1300776301
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 9563732504
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12547923845
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 9563792303
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12547686379
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 17426661930
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12547713786
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 2763450503
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 16510014185
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 16510131924
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 16510065604
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12547907297
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12547612968
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12547880344
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 9533204862
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 11037737603
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12547610902
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12403117347
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12547722048
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12547723958
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12690377058
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 9563933005
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12547912331
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12402866426
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 9563929150
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 9563592015
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 2065073304
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12547744474
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12547903126
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12547946441
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 9179400902
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12547934814
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12403108556
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12547869275
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12547623031
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 15802913599
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12362755653
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12547717588
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12547802599
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12547742914
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 9563589412
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 9563928814
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 9563943869
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12547611902
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12547710142
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12403123478
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 13548373916
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12547958173
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12362719112
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12362729664
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12362715122
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12547885414
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12402880727
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12547788046
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 13712003725
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 17426559318
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 18762815166
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 16510119698
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 242213983
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 18731751375
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 17635101544
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 11037285276
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 17634971192
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 17634976132
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 17635100176
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12547759345
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 7953178806
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 8214518612
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12547765688
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12547628206
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12403128979
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12547835552
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12547955968
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12547904130
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12362742605
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12403125031
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12547939521
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 10101314593
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 147741899
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12403149476
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12547619597
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12547873239
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12547878551
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12547762260
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12547730548
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12547906055
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12547891865
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12547945437
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12547791818
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12547962333
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12547726469
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12547858920
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 6031071050
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 6034439645
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12516780409
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12547857627
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 2982170348
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 6031075931
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 2065073006
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 9563782085
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12547747767
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 4463059046
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 9563798159
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 6031471489
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 17496629176
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 17496626965
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 6418215420
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 9563783367
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12547775926
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12547900132
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12547898642
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12547913605
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12362742023
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 9563585363
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12547755035
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 2065073565
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12362721759
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12403122231
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12362756875
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12362750379
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12362737732
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 8158186627
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12614438050
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12362731343
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12362756234
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12547933134
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 13580349573
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12362728616
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 16510162216
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12547864392
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12547927476
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12547677544
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 9563733154
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12547895318
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12547648115
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12547624513
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12547653122
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12403187607
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12547938071
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 9563940860
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 9563783751
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 1403936511
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12547720799
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 2434785466
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12547931492
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 15264880432
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 245630713
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 9563940572
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12547922096
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 18828480564
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12403170142
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12403176967
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12403168125
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 8214518056
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 678262230
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 9563792119
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 11037285611
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 18391555940
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12547614076
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12402872847
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12547680492
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12547676124
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 8360620314
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12547918142
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 9563780895
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 9563782855
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12547943042
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 9563810811
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 9563789443
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12547660764
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12547669982
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12547773588
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 14378889100
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12547752063
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 9563792512
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12547729462
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12547890265
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12547920903
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12547799466
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12547865955
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 3113323162
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12547671825
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12547769075
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 10594128624
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 14051022203
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 6031094681
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 16510052092
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12547953943
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12403114823
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12547696294
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12547637425
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12547684921
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 242856226
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 484211948
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12547772095
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 574244875
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 4505798638
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12547789133
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 2982169837
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12402919621
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12547766862
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 8214518341
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12547940688
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12547928708
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 3113323162
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12547654897
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 9563941846
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 134089777280156
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12547901252
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12403127173
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12547683636
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 9563725822
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 9563732807
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12547916987
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12403119761
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 123707692298451
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12403129848
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12403178389
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12362722516
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12403122907
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12362688080
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12402866961
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 84711654791155
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12547646754
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12547749390
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12547919713
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12547944112
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12201347372
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12547751238
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12547950179
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 9563783938
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12547795050
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 8159018546
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12547714744
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12547633873
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12547786898
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 9563784935
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 8214517790
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12547760853
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 9563818849
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 12547870972
	},
	{
		Type = "Form",
		FlipbookType = 1,
		TextureId = 6654201754
	}
}
