return {
	{
		Type = "FullWidth",
		FlipbookType = 1,
		TextureId = 147887593
	},
	{
		Type = "FullWidth",
		FlipbookType = 1,
		TextureId = 13912497794
	},
	{
		Type = "FullWidth",
		FlipbookType = 1,
		TextureId = 7367444684
	},
	{
		Type = "FullWidth",
		FlipbookType = 1,
		TextureId = 15231271662
	},
	{
		Type = "FullWidth",
		FlipbookType = 1,
		TextureId = 15414217272
	},
	{
		Type = "FullWidth",
		FlipbookType = 1,
		TextureId = 15414248015
	},
	{
		Type = "FullWidth",
		FlipbookType = 1,
		TextureId = 15311536323
	},
	{
		Type = "FullWidth",
		FlipbookType = 1,
		TextureId = 15414495037
	},
	{
		Type = "FullWidth",
		FlipbookType = 1,
		TextureId = 15414234374
	},
	{
		Type = "FullWidth",
		FlipbookType = 1,
		TextureId = 6171439278
	},
	{
		Type = "FullWidth",
		FlipbookType = 1,
		TextureId = 15414274468
	},
	{
		Type = "FullWidth",
		FlipbookType = 1,
		TextureId = 11201541666
	},
	{
		Type = "FullWidth",
		FlipbookType = 1,
		TextureId = 114626273186522
	},
	{
		Type = "FullWidth",
		FlipbookType = 1,
		TextureId = 6277012948
	},
	{
		Type = "FullWidth",
		FlipbookType = 1,
		TextureId = 13005707289
	},
	{
		Type = "FullWidth",
		FlipbookType = 1,
		TextureId = 9031170095
	},
	{
		Type = "FullWidth",
		FlipbookType = 1,
		TextureId = 13912498940
	},
	{
		Type = "FullWidth",
		FlipbookType = 1,
		TextureId = 1178029070
	},
	{
		Type = "FullWidth",
		FlipbookType = 1,
		TextureId = 15414790052
	},
	{
		Type = "FullWidth",
		FlipbookType = 1,
		TextureId = 15414656170
	},
	{
		Type = "FullWidth",
		FlipbookType = 1,
		TextureId = 6794148037
	},
	{
		Type = "FullWidth",
		FlipbookType = 1,
		TextureId = 13912539607
	},
	{
		Type = "FullWidth",
		FlipbookType = 1,
		TextureId = 268548709
	},
	{
		Type = "FullWidth",
		FlipbookType = 1,
		TextureId = 14048594088
	},
	{
		Type = "FullWidth",
		FlipbookType = 1,
		TextureId = 13912500373
	},
	{
		Type = "FullWidth",
		FlipbookType = 1,
		TextureId = 406192556
	},
	{
		Type = "FullWidth",
		FlipbookType = 1,
		TextureId = 10044280909
	},
	{
		Type = "FullWidth",
		FlipbookType = 1,
		TextureId = 4755479586
	},
	{
		Type = "FullWidth",
		FlipbookType = 1,
		TextureId = 411269072
	},
	{
		Type = "FullWidth",
		FlipbookType = 1,
		TextureId = 255160946
	},
	{
		Type = "FullWidth",
		FlipbookType = 1,
		TextureId = 7994628963
	},
	{
		Type = "FullWidth",
		FlipbookType = 1,
		TextureId = 11201539270
	},
	{
		Type = "FullWidth",
		FlipbookType = 1,
		TextureId = 1078637959
	},
	{
		Type = "FullWidth",
		FlipbookType = 1,
		TextureId = 12906121944
	},
	{
		Type = "FullWidth",
		FlipbookType = 1,
		TextureId = 4709281435
	},
	{
		Type = "FullWidth",
		FlipbookType = 1,
		TextureId = 811122220
	},
	{
		Type = "FullWidth",
		FlipbookType = 1,
		TextureId = 501546562
	},
	{
		Type = "FullWidth",
		FlipbookType = 1,
		TextureId = 16510192933
	},
	{
		Type = "FullWidth",
		FlipbookType = 1,
		TextureId = 1350523412
	},
	{
		Type = "FullWidth",
		FlipbookType = 1,
		TextureId = 177349309
	},
	{
		Type = "FullWidth",
		FlipbookType = 1,
		TextureId = 12239817548
	},
	{
		Type = "FullWidth",
		FlipbookType = 1,
		TextureId = 14117434366
	},
	{
		Type = "FullWidth",
		FlipbookType = 1,
		TextureId = 11976314748
	},
	{
		Type = "FullWidth",
		FlipbookType = 1,
		TextureId = 3211146752
	},
	{
		Type = "FullWidth",
		FlipbookType = 1,
		TextureId = 56366121
	},
	{
		Type = "FullWidth",
		FlipbookType = 1,
		TextureId = 56897545
	},
	{
		Type = "FullWidth",
		FlipbookType = 1,
		TextureId = 5722422984
	},
	{
		Type = "FullWidth",
		FlipbookType = 1,
		TextureId = 9238805458
	},
	{
		Type = "FullWidth",
		FlipbookType = 1,
		TextureId = 4504366173
	},
	{
		Type = "FullWidth",
		FlipbookType = 1,
		TextureId = 38852608
	},
	{
		Type = "FullWidth",
		FlipbookType = 1,
		TextureId = 11201544574
	},
	{
		Type = "FullWidth",
		FlipbookType = 1,
		TextureId = 14117432455
	},
	{
		Type = "FullWidth",
		FlipbookType = 1,
		TextureId = 1276468232
	},
	{
		Type = "FullWidth",
		FlipbookType = 1,
		TextureId = 410786214
	},
	{
		Type = "FullWidth",
		FlipbookType = 1,
		TextureId = 4512463057
	},
	{
		Type = "FullWidth",
		FlipbookType = 1,
		TextureId = 4504367541
	},
	{
		Type = "FullWidth",
		FlipbookType = 1,
		TextureId = 1112726928
	},
	{
		Type = "FullWidth",
		FlipbookType = 1,
		TextureId = 1337243068
	},
	{
		Type = "FullWidth",
		FlipbookType = 1,
		TextureId = 49942836
	},
	{
		Type = "FullWidth",
		FlipbookType = 1,
		TextureId = 112551503140860
	},
	{
		Type = "FullWidth",
		FlipbookType = 1,
		TextureId = 100292678213508
	},
	{
		Type = "FullWidth",
		FlipbookType = 1,
		TextureId = 384954302
	},
	{
		Type = "FullWidth",
		FlipbookType = 1,
		TextureId = 255161091
	},
	{
		Type = "FullWidth",
		FlipbookType = 1,
		TextureId = 17227331490
	},
	{
		Type = "FullWidth",
		FlipbookType = 1,
		TextureId = 398139001
	},
	{
		Type = "FullWidth",
		FlipbookType = 1,
		TextureId = 228322184
	},
	{
		Type = "FullWidth",
		FlipbookType = 1,
		TextureId = 125130865636154
	},
	{
		Type = "FullWidth",
		FlipbookType = 1,
		TextureId = 1467654679
	},
	{
		Type = "FullWidth",
		FlipbookType = 1,
		TextureId = 71062791251209
	},
	{
		Type = "FullWidth",
		FlipbookType = 1,
		TextureId = 82028783487343
	},
	{
		Type = "FullWidth",
		FlipbookType = 1,
		TextureId = 16510058099
	},
	{
		Type = "FullWidth",
		FlipbookType = 1,
		TextureId = 16510151107
	},
	{
		Type = "FullWidth",
		FlipbookType = 1,
		TextureId = 135586203185317
	},
	{
		Type = "FullWidth",
		FlipbookType = 1,
		TextureId = 414284775
	},
	{
		Type = "FullWidth",
		FlipbookType = 1,
		TextureId = 76990331
	},
	{
		Type = "FullWidth",
		FlipbookType = 1,
		TextureId = 414284607
	},
	{
		Type = "FullWidth",
		FlipbookType = 1,
		TextureId = 388415152
	},
	{
		Type = "FullWidth",
		FlipbookType = 1,
		TextureId = 81343082272470
	},
	{
		Type = "FullWidth",
		FlipbookType = 1,
		TextureId = 5889822044
	},
	{
		Type = "FullWidth",
		FlipbookType = 1,
		TextureId = 101052745199409
	},
	{
		Type = "FullWidth",
		FlipbookType = 1,
		TextureId = 17019604370
	},
	{
		Type = "FullWidth",
		FlipbookType = 1,
		TextureId = 255188888
	},
	{
		Type = "FullWidth",
		FlipbookType = 1,
		TextureId = 5889857268
	},
	{
		Type = "FullWidth",
		FlipbookType = 1,
		TextureId = 16510188813
	},
	{
		Type = "FullWidth",
		FlipbookType = 1,
		TextureId = 14315545709
	},
	{
		Type = "FullWidth",
		FlipbookType = 1,
		TextureId = 281763734
	},
	{
		Type = "FullWidth",
		FlipbookType = 1,
		TextureId = 14050964725
	},
	{
		Type = "FullWidth",
		FlipbookType = 1,
		TextureId = 27899086
	},
	{
		Type = "FullWidth",
		FlipbookType = 1,
		TextureId = 5638199267
	},
	{
		Type = "FullWidth",
		FlipbookType = 1,
		TextureId = 17402453778
	},
	{
		Type = "FullWidth",
		FlipbookType = 1,
		TextureId = 186399083
	},
	{
		Type = "FullWidth",
		FlipbookType = 1,
		TextureId = 79443127
	},
	{
		Type = "FullWidth",
		FlipbookType = 1,
		TextureId = 17227322185
	},
	{
		Type = "FullWidth",
		FlipbookType = 1,
		TextureId = 14050873440
	},
	{
		Type = "FullWidth",
		FlipbookType = 1,
		TextureId = 18323333728
	},
	{
		Type = "FullWidth",
		FlipbookType = 1,
		TextureId = 299427194
	},
	{
		Type = "FullWidth",
		FlipbookType = 1,
		TextureId = 27690789
	},
	{
		Type = "FullWidth",
		FlipbookType = 1,
		TextureId = 4887918429
	},
	{
		Type = "FullWidth",
		FlipbookType = 1,
		TextureId = 14590161735
	},
	{
		Type = "FullWidth",
		FlipbookType = 1,
		TextureId = 321649566
	},
	{
		Type = "FullWidth",
		FlipbookType = 1,
		TextureId = 10036236958
	},
	{
		Type = "FullWidth",
		FlipbookType = 1,
		TextureId = 14590139453
	},
	{
		Type = "FullWidth",
		FlipbookType = 1,
		TextureId = 27897921
	},
	{
		Type = "FullWidth",
		FlipbookType = 1,
		TextureId = 3186190770
	},
	{
		Type = "FullWidth",
		FlipbookType = 1,
		TextureId = 255187041
	},
	{
		Type = "FullWidth",
		FlipbookType = 1,
		TextureId = 7850765439
	},
	{
		Type = "FullWidth",
		FlipbookType = 1,
		TextureId = 12521426513
	},
	{
		Type = "FullWidth",
		FlipbookType = 1,
		TextureId = 225666521
	},
	{
		Type = "FullWidth",
		FlipbookType = 1,
		TextureId = 1464094791
	},
	{
		Type = "FullWidth",
		FlipbookType = 1,
		TextureId = 14590170889
	},
	{
		Type = "FullWidth",
		FlipbookType = 1,
		TextureId = 140061140880341
	},
	{
		Type = "FullWidth",
		FlipbookType = 1,
		TextureId = 5173933868
	},
	{
		Type = "FullWidth",
		FlipbookType = 1,
		TextureId = 14261224221
	},
	{
		Type = "FullWidth",
		FlipbookType = 1,
		TextureId = 110350224769481
	},
	{
		Type = "FullWidth",
		FlipbookType = 1,
		TextureId = 12417426090
	},
	{
		Type = "FullWidth",
		FlipbookType = 1,
		TextureId = 2930247814
	},
	{
		Type = "FullWidth",
		FlipbookType = 1,
		TextureId = 12353440665
	},
	{
		Type = "FullWidth",
		FlipbookType = 1,
		TextureId = 6372755229
	}
}
