return {
	{
		Type = "Misc",
		FlipbookType = 1,
		TextureId = 4513115659
	},
	{
		Type = "Misc",
		FlipbookType = 1,
		TextureId = 397459035
	},
	{
		Type = "Misc",
		FlipbookType = 1,
		TextureId = 8546937977
	},
	{
		Type = "Misc",
		FlipbookType = 1,
		TextureId = 7994997277
	},
	{
		Type = "Misc",
		FlipbookType = 1,
		TextureId = 16075039597
	},
	{
		Type = "Misc",
		FlipbookType = 1,
		TextureId = 16995596040
	},
	{
		Type = "Misc",
		FlipbookType = 1,
		TextureId = 6671348341
	},
	{
		Type = "Misc",
		FlipbookType = 1,
		TextureId = 16056962360
	},
	{
		Type = "Misc",
		FlipbookType = 1,
		TextureId = 98328979957906
	},
	{
		Type = "Misc",
		FlipbookType = 1,
		TextureId = 93999037974333
	},
	{
		Type = "Misc",
		FlipbookType = 1,
		TextureId = 6203493685
	},
	{
		Type = "Misc",
		FlipbookType = 1,
		TextureId = 131256164389542
	},
	{
		Type = "Misc",
		FlipbookType = 1,
		TextureId = 128697005192835
	},
	{
		Type = "Misc",
		FlipbookType = 1,
		TextureId = 14242276165
	},
	{
		Type = "Misc",
		FlipbookType = 1,
		TextureId = 13326678344
	},
	{
		Type = "Misc",
		FlipbookType = 1,
		TextureId = 8539134773
	},
	{
		Type = "Misc",
		FlipbookType = 1,
		TextureId = 135834748466518
	},
	{
		Type = "Misc",
		FlipbookType = 1,
		TextureId = 79722475227859
	},
	{
		Type = "Misc",
		FlipbookType = 1,
		TextureId = 16509992918
	},
	{
		Type = "Misc",
		FlipbookType = 1,
		TextureId = 256038800
	},
	{
		Type = "Misc",
		FlipbookType = 1,
		TextureId = 102124677
	},
	{
		Type = "Misc",
		FlipbookType = 1,
		TextureId = 5747127665
	},
	{
		Type = "Misc",
		FlipbookType = 1,
		TextureId = 127008529900163
	},
	{
		Type = "Misc",
		FlipbookType = 1,
		TextureId = 130243787399825
	},
	{
		Type = "Misc",
		FlipbookType = 1,
		TextureId = 13712004842
	},
	{
		Type = "Misc",
		FlipbookType = 1,
		TextureId = 3234221039
	},
	{
		Type = "Misc",
		FlipbookType = 1,
		TextureId = 16078149711
	},
	{
		Type = "Misc",
		FlipbookType = 1,
		TextureId = 14049239712
	},
	{
		Type = "Misc",
		FlipbookType = 1,
		TextureId = 13267054240
	},
	{
		Type = "Misc",
		FlipbookType = 1,
		TextureId = 9533344415
	},
	{
		Type = "Misc",
		FlipbookType = 1,
		TextureId = 8376012789
	},
	{
		Type = "Misc",
		FlipbookType = 1,
		TextureId = 12364604865
	},
	{
		Type = "Misc",
		FlipbookType = 1,
		TextureId = 6306268923
	},
	{
		Type = "Misc",
		FlipbookType = 1,
		TextureId = 16510074656
	},
	{
		Type = "Misc",
		FlipbookType = 1,
		TextureId = 16501436490
	},
	{
		Type = "Misc",
		FlipbookType = 1,
		TextureId = 16082650265
	},
	{
		Type = "Misc",
		FlipbookType = 1,
		TextureId = 17842357017
	},
	{
		Type = "Misc",
		FlipbookType = 1,
		TextureId = 116587227878774
	},
	{
		Type = "Misc",
		FlipbookType = 1,
		TextureId = 10926572594
	},
	{
		Type = "Misc",
		FlipbookType = 1,
		TextureId = 12310930133
	},
	{
		Type = "Misc",
		FlipbookType = 1,
		TextureId = 6758595484
	},
	{
		Type = "Misc",
		FlipbookType = 1,
		TextureId = 11123532151
	},
	{
		Type = "Misc",
		FlipbookType = 1,
		TextureId = 8379838161
	},
	{
		Type = "Misc",
		FlipbookType = 1,
		TextureId = 6937548846
	},
	{
		Type = "Misc",
		FlipbookType = 1,
		TextureId = 8502239364
	},
	{
		Type = "Misc",
		FlipbookType = 1,
		TextureId = 6174863093
	},
	{
		Type = "Misc",
		FlipbookType = 1,
		TextureId = 11609486996
	},
	{
		Type = "Misc",
		FlipbookType = 1,
		TextureId = 13991337233
	},
	{
		Type = "Misc",
		FlipbookType = 1,
		TextureId = 18612090634
	},
	{
		Type = "Misc",
		FlipbookType = 1,
		TextureId = 18611124377
	},
	{
		Type = "Misc",
		FlipbookType = 1,
		TextureId = 18610582975
	},
	{
		Type = "Misc",
		FlipbookType = 1,
		TextureId = 18484510573
	},
	{
		Type = "Misc",
		FlipbookType = 1,
		TextureId = 18423619252
	}
}
