return {
	{
		Type = "Misc",
		FlipbookType = 4,
		TextureId = 12890944256
	},
	{
		Type = "Misc",
		FlipbookType = 4,
		TextureId = 16511653838
	},
	{
		Type = "Misc",
		FlipbookType = 4,
		TextureId = 17635358235
	},
	{
		Type = "Misc",
		FlipbookType = 4,
		TextureId = 18102807707
	},
	{
		Type = "Misc",
		FlipbookType = 4,
		TextureId = 18102805523
	},
	{
		Type = "Misc",
		FlipbookType = 4,
		TextureId = 121821632609494
	},
	{
		Type = "Misc",
		FlipbookType = 4,
		TextureId = 70513431100180
	},
	{
		Type = "Misc",
		FlipbookType = 4,
		TextureId = 95140503372994
	},
	{
		Type = "Misc",
		FlipbookType = 4,
		TextureId = 117453741701172
	},
	{
		Type = "Misc",
		FlipbookType = 4,
		TextureId = 138739980771660
	},
	{
		Type = "Misc",
		FlipbookType = 4,
		TextureId = 17713866288
	},
	{
		Type = "Misc",
		FlipbookType = 4,
		TextureId = 15414630817
	},
	{
		Type = "Misc",
		FlipbookType = 4,
		TextureId = 123998391988781
	},
	{
		Type = "Misc",
		FlipbookType = 4,
		TextureId = 14990829312
	},
	{
		Type = "Misc",
		FlipbookType = 4,
		TextureId = 75781711823358
	},
	{
		Type = "Misc",
		FlipbookType = 4,
		TextureId = 80103256348315
	},
	{
		Type = "Misc",
		FlipbookType = 4,
		TextureId = 95304904398822
	},
	{
		Type = "Misc",
		FlipbookType = 4,
		TextureId = 138239163525254
	},
	{
		Type = "Misc",
		FlipbookType = 4,
		TextureId = 117784751087297
	},
	{
		Type = "Misc",
		FlipbookType = 4,
		TextureId = 116167345196456
	},
	{
		Type = "Misc",
		FlipbookType = 4,
		TextureId = 86779984483816
	},
	{
		Type = "Misc",
		FlipbookType = 4,
		TextureId = 109017652253159
	},
	{
		Type = "Misc",
		FlipbookType = 4,
		TextureId = 137710412554130
	},
	{
		Type = "Misc",
		FlipbookType = 4,
		TextureId = 132161450209006
	},
	{
		Type = "Misc",
		FlipbookType = 4,
		TextureId = 122073922365921
	},
	{
		Type = "Misc",
		FlipbookType = 2,
		TextureId = 98807301396500
	},
	{
		Type = "Misc",
		FlipbookType = 2,
		TextureId = 140276501876592
	},
	{
		Type = "Misc",
		FlipbookType = 2,
		TextureId = 9169641230
	},
	{
		Type = "Misc",
		FlipbookType = 2,
		TextureId = 16504172101
	},
	{
		Type = "Misc",
		FlipbookType = 8,
		TextureId = 14197058775
	},
	{
		Type = "Misc",
		FlipbookType = 8,
		TextureId = 10762069832
	},
	{
		Type = "Misc",
		FlipbookType = 8,
		TextureId = 10547506060
	},
	{
		Type = "Misc",
		FlipbookType = 8,
		TextureId = 10762165826
	},
	{
		Type = "Misc",
		FlipbookType = 8,
		TextureId = 15229101950
	},
	{
		Type = "Misc",
		FlipbookType = 8,
		TextureId = 84434739678137
	},
	{
		Type = "Misc",
		FlipbookType = 8,
		TextureId = 10762151233
	},
	{
		Type = "Misc",
		FlipbookType = 8,
		TextureId = 119159832478793
	},
	{
		Type = "Misc",
		FlipbookType = 8,
		TextureId = 121604844293818
	},
	{
		Type = "Misc",
		FlipbookType = 8,
		TextureId = 14197063144
	},
	{
		Type = "Misc",
		FlipbookType = 8,
		TextureId = 133046681582945
	},
	{
		Type = "Misc",
		FlipbookType = 8,
		TextureId = 6430084331
	},
	{
		Type = "Misc",
		FlipbookType = 8,
		TextureId = 14004727601
	},
	{
		Type = "Misc",
		FlipbookType = 8,
		TextureId = 16511415159
	},
	{
		Type = "Misc",
		FlipbookType = 8,
		TextureId = 18612931430
	},
	{
		Type = "Misc",
		FlipbookType = 8,
		TextureId = 16511904372
	}
}
