return {
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 8952343799
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 11724494033
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 11724484287
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 11724492591
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 14619167655
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 11724490933
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 8952345829
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 11579028784
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 11724363984
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 15501870094
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 11724347840
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 8952350386
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 13935216671
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 8944348380
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 8944343954
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 12939184502
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 8944196730
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 8952353573
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 1084970835
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 8944372435
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 11932690139
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 1053546634
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 8952342372
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 8944358961
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 11037479900
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 8944369029
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 11724234231
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 11724358851
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 11724353198
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 11724200186
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 14973884209
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 11724433858
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 11724362038
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 11425477167
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 12822942887
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 11037286228
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 12015546676
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 8952268539
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 11724477415
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 15501783468
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 11724418667
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 89467043003546
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 8944363782
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 15501861373
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 11579029023
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 15501901188
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 8944221997
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 14702835078
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 8944355101
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 11724443775
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 11724483198
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 18355979113
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 89480767232810
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 8944435897
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 15501781612
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 12105193694
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 18256370999
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 14816531981
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 15501780826
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 18836944836
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 17230625999
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 15501811581
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 15501803559
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 8944366260
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 15501860320
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 8952281337
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 15501785822
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 15501843651
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 15501866280
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 13647185221
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 14032952906
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 17391818367
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 15432520301
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 13948669435
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 15501842854
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 15501868294
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 13580346182
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 124535207786292
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 11724365356
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 8952352063
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 15501859329
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 15501788728
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 15501782488
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 10317000242
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 15501875766
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 15501810552
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 15501867037
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 15501796095
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 15501797918
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 4791826133
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 15501796984
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 15501787002
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 15501856654
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 6490035152
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 15501873301
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 14197583306
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 15501795179
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 15501777595
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 15501858493
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 7668084440
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 14197626379
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 16366023815
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 10090193900
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 8214517377
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 15501785112
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 15501874035
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 18198069501
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 15501784243
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 11828156780
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 15022616392
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 15501809370
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 18356334814
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 11724460265
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 15501857604
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 8952309558
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 270446290
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 13427689179
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 15501855369
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 134531274
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 100545368205823
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 15548827059
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 13592990832
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 8220403971
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 9504165696
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 17062451848
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 15501804517
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 80768860709156
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 507021722
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 11815755770
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 8114033129
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 243728206
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 15501864149
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 16620522804
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 15501874945
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 107264993528590
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 8180428772
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 6909741538
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 80461772858840
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 14969367343
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 15057225013
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 16511986084
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 15267996400
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 17068400400
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 7556127048
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 8611887703
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 82921243876307
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 11815755770
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 1164713030
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 2450830110
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 14723885579
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 15267995469
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 16511961942
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 7948615545
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 15267958329
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 13908198788
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 15267994078
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 15452013947
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 15786345729
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 12386386944
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 15214318786
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 15267976180
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 14780651881
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 14198353638
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 8120666025
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 13161986324
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 244221535
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 17211298816
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 15267983023
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 18836673412
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 15267984568
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 15267978808
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 15773612675
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 14900573154
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 3052949762
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 14118135260
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 16511998441
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 10911246475
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 12684715885
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 17268259842
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 17233735787
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 15785273325
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 15840018597
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 136177821208948
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 15267974440
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 7216849325
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 16504678311
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 14197929950
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 17255319890
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 18964235118
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 15268036910
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 2784679817
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 17085199891
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 8905832887
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 15580440964
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 8187307788
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 6479253935
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 14049988179
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 10335418884
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 1847258023
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 108410399780728
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 15267981562
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 7216849594
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 13366348510
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 15267947048
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 8210105223
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 669133414
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 15246593122
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 8037777212
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 37037765
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 108523870700360
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 118282298958693
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 105480580622301
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 13416568539
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 14590086212
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 16511623380
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 14684195806
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 18964235304
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 13575704611
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 136183361604886
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 15267988769
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 15058066935
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 13366353306
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 12159555294
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 15268042395
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 13275495915
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 15267960965
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 15267986070
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 116403060004639
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 112652574879204
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 1454292685
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 79476683599471
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 15267964963
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 75202463
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 917186750
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 7216854591
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 14006787869
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 13463792226
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 9509570418
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 97371691119032
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 107783098191892
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 17062454806
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 15267967428
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 9563725604
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 14813420032
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 17230437889
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 115470063682950
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 11410124087
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 7216849075
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 16608943230
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 12386392796
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 13008221535
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 243728166
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 14657035983
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 15394997710
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 131664964955693
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 15267959767
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 15439360454
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 12598593932
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 7216853637
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 8180428772
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 14128174572
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 7216848960
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 15513493035
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 18454329983
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 15267955654
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 15372682647
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 7216848832
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 5946093983
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 15027630128
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 13368682130
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 271370648
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 1598630577
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 117540403634999
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 12402859532
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 8189326437
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 14006783533
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 15267992198
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 106290110024655
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 15267970904
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 298984512
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 82987273435737
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 15600777303
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 15267987555
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 15495277841
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 7216848699
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 80007163276893
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 91924863141962
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 15267977235
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 13711999895
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 90246218106752
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 15267962251
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 16444981264
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 15267980155
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 7216849703
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 14221498728
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 10598374841
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 13271102367
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 13580351747
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 9186694978
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 15267968986
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 16512006463
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 17376619574
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 15267963470
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 13271628051
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 17413732419
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 84427792951578
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 16511964424
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 917186750
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 87009648602330
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 4463216225
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 15268038689
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 17062452122
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 10637682258
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 13903581452
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 917207599
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 3060556198
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 111352593268650
	},
	{
		Type = "Shine",
		FlipbookType = 1,
		TextureId = 12363796862
	}
}
