return {
	{
		Type = "Shine",
		FlipbookType = 4,
		TextureId = 114699340835751
	},
	{
		Type = "Shine",
		FlipbookType = 4,
		TextureId = 16940423887
	},
	{
		Type = "Shine",
		FlipbookType = 4,
		TextureId = 13753850869
	},
	{
		Type = "Shine",
		FlipbookType = 4,
		TextureId = 17000879366
	},
	{
		Type = "Shine",
		FlipbookType = 4,
		TextureId = 15796221784
	},
	{
		Type = "Shine",
		FlipbookType = 4,
		TextureId = 14454506302
	},
	{
		Type = "Shine",
		FlipbookType = 4,
		TextureId = 102017495370895
	},
	{
		Type = "Shine",
		FlipbookType = 4,
		TextureId = 125196793561851
	},
	{
		Type = "Shine",
		FlipbookType = 4,
		TextureId = 14379758359
	},
	{
		Type = "Shine",
		FlipbookType = 4,
		TextureId = 18440899130
	},
	{
		Type = "Shine",
		FlipbookType = 4,
		TextureId = 18718571124
	},
	{
		Type = "Shine",
		FlipbookType = 4,
		TextureId = 18441157729
	},
	{
		Type = "Shine",
		FlipbookType = 4,
		TextureId = 117386196464548
	},
	{
		Type = "Shine",
		FlipbookType = 4,
		TextureId = 103166710242399
	},
	{
		Type = "Shine",
		FlipbookType = 4,
		TextureId = 13189667061
	},
	{
		Type = "Shine",
		FlipbookType = 4,
		TextureId = 12452578181
	},
	{
		Type = "Shine",
		FlipbookType = 4,
		TextureId = 117847360319396
	},
	{
		Type = "Shine",
		FlipbookType = 4,
		TextureId = 12156297119
	},
	{
		Type = "Shine",
		FlipbookType = 4,
		TextureId = 94244023661545
	},
	{
		Type = "Shine",
		FlipbookType = 4,
		TextureId = 116403982640393
	},
	{
		Type = "Shine",
		FlipbookType = 4,
		TextureId = 15783804541
	},
	{
		Type = "Shine",
		FlipbookType = 4,
		TextureId = 13448020277
	},
	{
		Type = "Shine",
		FlipbookType = 4,
		TextureId = 15268170416
	},
	{
		Type = "Shine",
		FlipbookType = 4,
		TextureId = 8733414465
	},
	{
		Type = "Shine",
		FlipbookType = 4,
		TextureId = 17517651294
	},
	{
		Type = "Shine",
		FlipbookType = 4,
		TextureId = 79705556595545
	},
	{
		Type = "Shine",
		FlipbookType = 4,
		TextureId = 137439303725875
	},
	{
		Type = "Shine",
		FlipbookType = 4,
		TextureId = 92552711821642
	},
	{
		Type = "Shine",
		FlipbookType = 4,
		TextureId = 117665795699820
	},
	{
		Type = "Shine",
		FlipbookType = 4,
		TextureId = 89272816038619
	},
	{
		Type = "Shine",
		FlipbookType = 4,
		TextureId = 105427977618886
	},
	{
		Type = "Shine",
		FlipbookType = 4,
		TextureId = 130700397415341
	},
	{
		Type = "Shine",
		FlipbookType = 8,
		TextureId = 72766370524616
	},
	{
		Type = "Shine",
		FlipbookType = 8,
		TextureId = 104287260780961
	},
	{
		Type = "Shine",
		FlipbookType = 8,
		TextureId = 120724457343104
	},
	{
		Type = "Shine",
		FlipbookType = 8,
		TextureId = 11676151428
	},
	{
		Type = "Shine",
		FlipbookType = 2,
		TextureId = 124514297394536
	},
	{
		Type = "Shine",
		FlipbookType = 2,
		TextureId = 13495497858
	},
	{
		Type = "Shine",
		FlipbookType = 2,
		TextureId = 82555475355022
	},
	{
		Type = "Shine",
		FlipbookType = 2,
		TextureId = 14052685115
	},
	{
		Type = "Shine",
		FlipbookType = 2,
		TextureId = 16669702010
	},
	{
		Type = "Shine",
		FlipbookType = 2,
		TextureId = 78694460034696
	},
	{
		Type = "Shine",
		FlipbookType = 2,
		TextureId = 94431438472232
	},
	{
		Type = "Shine",
		FlipbookType = 2,
		TextureId = 12224333321
	},
	{
		Type = "Shine",
		FlipbookType = 2,
		TextureId = 139959661465737
	},
	{
		Type = "Shine",
		FlipbookType = 2,
		TextureId = 71363205937532
	},
	{
		Type = "Shine",
		FlipbookType = 2,
		TextureId = 15947089313
	},
	{
		Type = "Shine",
		FlipbookType = 2,
		TextureId = 18964234996
	}
}
