return {
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 15501913594
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 15501988571
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 18731724655
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 16511734784
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 11724219578
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 8214519194
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 18921717035
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 139912049469070
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 83182096707138
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 137073597488305
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 17866575849
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 134803974801139
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 121369557863094
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 8099267640
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 13486413277
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 17511006627
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 9533206478
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 72653288871823
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 124479768734322
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 8214518193
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 9533205153
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 9533205006
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 8095997435
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 97601800196735
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 15501981529
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 15501979534
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 15501839106
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 17230554108
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 8214518833
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 86680616725095
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 128773079087704
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 15501841237
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 15501832910
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 15501817914
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 15501972748
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 15501844778
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 15501977831
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 14792302231
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 15501987100
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 17230633831
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 17230610596
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 15501826519
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 15501994317
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 15501835499
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 15501834687
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 15501829731
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 129880122276615
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 15501914469
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 15501915179
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 15501825522
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 15501986108
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 17230617957
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 17233788823
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 14221278722
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 15502004660
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 15501982270
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 17230577467
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 107563407849922
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 111047838522006
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 134558124229568
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 119764335151801
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 14197211075
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 88185001751416
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 71338214928699
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 92843011365884
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 76217104129357
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 129434355768283
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 11902425479
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 111589920618215
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 9533205508
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 106866141379050
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 12362738407
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 15501980634
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 15501833943
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 15501836301
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 15501903313
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 15501906010
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 17230564760
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 71930220744957
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 12403135098
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 12362747042
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 110193486541760
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 15501845740
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 14197236586
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 14119772788
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 13280229340
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 13280232109
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 12362773668
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 99902889120231
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 16878130833
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 13280240913
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 122808252444369
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 81400439625843
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 71655002513139
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 136756889473734
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 16511918707
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 11902389822
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 125462816766133
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 16446615384
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 139136564191390
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 119187610315484
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 83949941285638
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 80150875212520
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 124287724788266
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 89496121135821
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 15501840173
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 15501841950
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 90642301292470
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 14221329252
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 16446611978
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 119939087084036
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 135581211362295
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 13688846194
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 14197216945
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 90153176003587
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 17230533536
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 75874239524186
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 15501928209
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 17230597915
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 112736182622635
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 131366030295010
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 17230525801
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 12403125823
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 12403132387
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 88560666660119
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 14197229649
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 9533205744
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 17511004183
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 12403133859
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 111373150574454
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 11902401640
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 12362769346
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 18391409702
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 12362764109
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 99918413814218
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 12675920331
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 140335729885408
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 18391493666
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 17426572844
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 85568077026769
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 82806823662496
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 14197348275
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 224019254
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 7216854161
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 17852245890
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 12362763160
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 223123319
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 11902428695
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 75598877436080
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 12362776683
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 79942350044433
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 9533206120
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 14197322805
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 12362774632
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 120197114002389
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 11902410656
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 109710995022660
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 124377248145448
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 116138574395443
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 9533205884
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 12362771118
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 18803010783
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 12402883115
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 14197316125
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 12403146281
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 17377587853
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 12403114323
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 12362720771
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 134799394748226
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 102148949350979
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 9533264910
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 125703415237328
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 12362768191
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 17630394991
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 12403130595
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 12362782096
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 12403137010
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 11902317248
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 564943383
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 14149522288
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 75759718124469
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 81619039902878
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 12362765032
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 12402871480
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 11902232976
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 12362775289
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 257228742
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 127817121
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 127817200
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 12362776008
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 16878137158
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 15868494793
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 12362766880
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 14197243565
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 18921751176
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 17426553699
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 12403146983
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 102222743448425
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 77825363667282
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 12403136226
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 12403133283
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 17635313861
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 17837865472
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 110616238659613
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 17426627122
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 136999003015785
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 131289392854639
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 73396121023189
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 106183158726625
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 12362783431
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 128868118139297
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 91738483473469
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 130890812031715
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 78300633972663
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 121601413517549
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 1928816167
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 111724750239368
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 12402928708
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 12402912430
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 103643526780671
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 73574466608885
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 135141028133816
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 112282882729962
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 125177827769037
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 12403143548
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 7216854028
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 13280240056
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 109135776353668
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 14197201511
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 12362702029
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 107418854370558
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 12403144779
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 112536024116381
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 16878166759
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 18391527082
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 94642151480448
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 18746917664
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 135228436795648
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 17426622391
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 87444313698910
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 11902378557
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 12362719770
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 691179887
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 95829570716137
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 12362745817
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 131954827538984
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 11902545845
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 108359596251756
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 17426619371
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 113584395506096
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 16878119374
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 16878129168
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 16878169825
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 17426615364
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 12362749008
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 100708312805540
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 12402882116
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 102367309102388
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 76475262724303
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 2384354542
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 14197192649
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 18435192461
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 12403139465
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 106532762843715
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 92606481798283
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 99168122269093
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 16878132157
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 12402911865
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 82634208863762
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 12402881551
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 12179045702
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 12402870681
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 123621823431078
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 75548700533773
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 16618677089
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 85330237770420
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 74267717275957
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 13556803456
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 126841848619080
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 17837655315
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 72172458554681
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 91448842457982
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 136291727650422
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 111905136096117
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 16924456285
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 18623319801
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 18623324962
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 12403140363
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 11902212788
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 127817178
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 13149649814
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 565056459
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 126440035426242
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 123314899160423
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 7948622386
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 12403131901
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 80959485106111
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 12362780784
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 100396643636322
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 131702476953975
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 120896998850693
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 121665727484427
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 14119772343
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 12403102126
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 357408298
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 11902368278
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 16494986663
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 11902439743
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 12402869217
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 794950602
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 14197272066
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 7207952712
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 17842467061
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 17841074130
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 14197257578
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 14197282370
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 16511726823
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 89613831210143
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 17243361926
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 138325705399982
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 17426578693
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 139580580206545
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 11902557897
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 14052947329
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 564938805
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 11902268345
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 12402884790
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 12403138547
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 136462169893755
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 70556913153050
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 102790439571584
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 94905972833658
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 16878080262
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 110974154905533
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 75733984111735
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 15268071837
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 81081149331665
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 16300304082
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 16878076248
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 109416220800089
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 100887971756500
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 14191668646
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 17243401293
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 14197309228
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 130807463044790
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 16924969332
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 102425379013314
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 14197333869
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 12403128022
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 7216853898
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 11902630396
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 15044756997
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 12444054132
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 86468821245483
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 111623010592158
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 12362784177
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 12403141153
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 11902304637
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 125485962153426
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 140248623110087
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 101415630152612
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 17826236534
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 77373159721092
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 564847326
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 14191651608
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 11902406031
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 120180279691243
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 113974948433764
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 90649252477858
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 138194271979463
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 14191659579
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 14197223901
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 12403135724
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 12547629571
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 125369583946174
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 133502584854431
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 18648347460
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 9733390
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 104968379808371
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 100392918604429
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 136488378522949
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 128389339609442
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 83016606478749
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 96458147030299
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 265788038
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 90964239058388
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 511898588
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 18391380989
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 15109315424
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 129316016149446
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 14197207222
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 12403115387
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 14197254601
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 12403155274
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 12402872168
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 12403137662
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 12362765929
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 14167239770
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 12403165446
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 71317674886631
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 101423825010627
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 17828635549
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 73592354394571
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 90657399709937
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 11902398938
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 71625533541727
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 123986680592541
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 122595310019657
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 118072404253090
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 114241902234463
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 110771358316729
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 87001521331112
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 12403116585
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 10225452993
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 95021516837022
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 103832117709724
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 79129682296813
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 11902285919
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 130325127087986
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 100505870999306
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 14197297037
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 12403099647
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 12403142404
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 14198043798
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 107470715921924
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 6897762276
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 111070876307110
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 12403141690
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 15518729175
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 12403072872
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 85593413197045
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 16850631336
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 11902281087
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 137684712495086
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 12402885547
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 14191644242
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 106189591371710
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 16850384679
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 81591229555708
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 12403147523
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 16397769425
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 118558273816607
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 11902581685
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 136674083788994
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 11902373427
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 12402888837
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 11902442693
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 11902327902
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 16511732405
	},
	{
		Type = "Sigil",
		FlipbookType = 1,
		TextureId = 13399941667
	}
}
