return {
	{
		Type = "Slash",
		FlipbookType = 1,
		TextureId = 14032864779
	},
	{
		Type = "Slash",
		FlipbookType = 1,
		TextureId = 8490559232
	},
	{
		Type = "Slash",
		FlipbookType = 1,
		TextureId = 15316493978
	},
	{
		Type = "Slash",
		FlipbookType = 1,
		TextureId = 14197491097
	},
	{
		Type = "Slash",
		FlipbookType = 1,
		TextureId = 14198091244
	},
	{
		Type = "Slash",
		FlipbookType = 1,
		TextureId = 17268350699
	},
	{
		Type = "Slash",
		FlipbookType = 1,
		TextureId = 77775297425294
	},
	{
		Type = "Slash",
		FlipbookType = 1,
		TextureId = 14200086275
	},
	{
		Type = "Slash",
		FlipbookType = 1,
		TextureId = 13280227271
	},
	{
		Type = "Slash",
		FlipbookType = 1,
		TextureId = 107279202345971
	},
	{
		Type = "Slash",
		FlipbookType = 1,
		TextureId = 9324968005
	},
	{
		Type = "Slash",
		FlipbookType = 1,
		TextureId = 122460061985642
	},
	{
		Type = "Slash",
		FlipbookType = 1,
		TextureId = 13548576250
	},
	{
		Type = "Slash",
		FlipbookType = 1,
		TextureId = 6250126210
	},
	{
		Type = "Slash",
		FlipbookType = 1,
		TextureId = 13580376896
	},
	{
		Type = "Slash",
		FlipbookType = 1,
		TextureId = 15728405620
	},
	{
		Type = "Slash",
		FlipbookType = 1,
		TextureId = 12402863039
	},
	{
		Type = "Slash",
		FlipbookType = 1,
		TextureId = 14242056438
	},
	{
		Type = "Slash",
		FlipbookType = 1,
		TextureId = 12922845759
	},
	{
		Type = "Slash",
		FlipbookType = 1,
		TextureId = 6897810667
	},
	{
		Type = "Slash",
		FlipbookType = 1,
		TextureId = 17388445124
	},
	{
		Type = "Slash",
		FlipbookType = 1,
		TextureId = 12690450233
	},
	{
		Type = "Slash",
		FlipbookType = 1,
		TextureId = 551638771
	},
	{
		Type = "Slash",
		FlipbookType = 1,
		TextureId = 12402878232
	},
	{
		Type = "Slash",
		FlipbookType = 1,
		TextureId = 16370338279
	},
	{
		Type = "Slash",
		FlipbookType = 1,
		TextureId = 10352551950
	},
	{
		Type = "Slash",
		FlipbookType = 1,
		TextureId = 13249988940
	},
	{
		Type = "Slash",
		FlipbookType = 1,
		TextureId = 12386374115
	},
	{
		Type = "Slash",
		FlipbookType = 1,
		TextureId = 8944405134
	},
	{
		Type = "Slash",
		FlipbookType = 1,
		TextureId = 10335155912
	},
	{
		Type = "Slash",
		FlipbookType = 1,
		TextureId = 16924973213
	},
	{
		Type = "Slash",
		FlipbookType = 1,
		TextureId = 12403113489
	},
	{
		Type = "Slash",
		FlipbookType = 1,
		TextureId = 11037067294
	},
	{
		Type = "Slash",
		FlipbookType = 1,
		TextureId = 15268215353
	},
	{
		Type = "Slash",
		FlipbookType = 1,
		TextureId = 16434901408
	},
	{
		Type = "Slash",
		FlipbookType = 1,
		TextureId = 10214381323
	},
	{
		Type = "Slash",
		FlipbookType = 1,
		TextureId = 13269732671
	},
	{
		Type = "Slash",
		FlipbookType = 1,
		TextureId = 14765899912
	},
	{
		Type = "Slash",
		FlipbookType = 1,
		TextureId = 135596833550213
	},
	{
		Type = "Slash",
		FlipbookType = 1,
		TextureId = 17223603454
	},
	{
		Type = "Slash",
		FlipbookType = 1,
		TextureId = 8096189152
	},
	{
		Type = "Slash",
		FlipbookType = 1,
		TextureId = 7092071889
	},
	{
		Type = "Slash",
		FlipbookType = 1,
		TextureId = 13688982493
	},
	{
		Type = "Slash",
		FlipbookType = 1,
		TextureId = 11724390442
	},
	{
		Type = "Slash",
		FlipbookType = 1,
		TextureId = 117762823938872
	},
	{
		Type = "Slash",
		FlipbookType = 1,
		TextureId = 8944251417
	},
	{
		Type = "Slash",
		FlipbookType = 1,
		TextureId = 9563708576
	},
	{
		Type = "Slash",
		FlipbookType = 1,
		TextureId = 9533204017
	},
	{
		Type = "Slash",
		FlipbookType = 1,
		TextureId = 1084965356
	},
	{
		Type = "Slash",
		FlipbookType = 1,
		TextureId = 11724291829
	},
	{
		Type = "Slash",
		FlipbookType = 1,
		TextureId = 12706180171
	},
	{
		Type = "Slash",
		FlipbookType = 1,
		TextureId = 10423609590
	},
	{
		Type = "Slash",
		FlipbookType = 1,
		TextureId = 10423599002
	},
	{
		Type = "Slash",
		FlipbookType = 1,
		TextureId = 13712006632
	},
	{
		Type = "Slash",
		FlipbookType = 1,
		TextureId = 18453345631
	},
	{
		Type = "Slash",
		FlipbookType = 1,
		TextureId = 13276348686
	},
	{
		Type = "Slash",
		FlipbookType = 1,
		TextureId = 15552205113
	},
	{
		Type = "Slash",
		FlipbookType = 1,
		TextureId = 8247973361
	},
	{
		Type = "Slash",
		FlipbookType = 1,
		TextureId = 17388366478
	},
	{
		Type = "Slash",
		FlipbookType = 1,
		TextureId = 12713358087
	},
	{
		Type = "Slash",
		FlipbookType = 1,
		TextureId = 2058077944
	},
	{
		Type = "Slash",
		FlipbookType = 1,
		TextureId = 16924640817
	},
	{
		Type = "Slash",
		FlipbookType = 1,
		TextureId = 1084977655
	},
	{
		Type = "Slash",
		FlipbookType = 1,
		TextureId = 1084996536
	},
	{
		Type = "Slash",
		FlipbookType = 1,
		TextureId = 16979588444
	},
	{
		Type = "Slash",
		FlipbookType = 1,
		TextureId = 12386371530
	},
	{
		Type = "Slash",
		FlipbookType = 1,
		TextureId = 13556795459
	},
	{
		Type = "Slash",
		FlipbookType = 1,
		TextureId = 15268211593
	},
	{
		Type = "Slash",
		FlipbookType = 1,
		TextureId = 13580336752
	},
	{
		Type = "Slash",
		FlipbookType = 1,
		TextureId = 15694390666
	},
	{
		Type = "Slash",
		FlipbookType = 1,
		TextureId = 14322954718
	},
	{
		Type = "Slash",
		FlipbookType = 1,
		TextureId = 6250126210
	},
	{
		Type = "Slash",
		FlipbookType = 1,
		TextureId = 15510257064
	},
	{
		Type = "Slash",
		FlipbookType = 1,
		TextureId = 80239165383797
	},
	{
		Type = "Slash",
		FlipbookType = 1,
		TextureId = 5700005718
	},
	{
		Type = "Slash",
		FlipbookType = 1,
		TextureId = 18403832786
	},
	{
		Type = "Slash",
		FlipbookType = 1,
		TextureId = 90157353623073
	},
	{
		Type = "Slash",
		FlipbookType = 1,
		TextureId = 82073447716302
	},
	{
		Type = "Slash",
		FlipbookType = 1,
		TextureId = 18453206591
	},
	{
		Type = "Slash",
		FlipbookType = 1,
		TextureId = 15683692190
	},
	{
		Type = "Slash",
		FlipbookType = 1,
		TextureId = 15683693744
	},
	{
		Type = "Slash",
		FlipbookType = 1,
		TextureId = 13832097149
	},
	{
		Type = "Slash",
		FlipbookType = 1,
		TextureId = 8084911316
	},
	{
		Type = "Slash",
		FlipbookType = 1,
		TextureId = 10365549704
	},
	{
		Type = "Slash",
		FlipbookType = 1,
		TextureId = 13938473088
	},
	{
		Type = "Slash",
		FlipbookType = 1,
		TextureId = 15811547630
	},
	{
		Type = "Slash",
		FlipbookType = 1,
		TextureId = 6569118042
	},
	{
		Type = "Slash",
		FlipbookType = 1,
		TextureId = 16445026823
	},
	{
		Type = "Slash",
		FlipbookType = 1,
		TextureId = 10195815698
	},
	{
		Type = "Slash",
		FlipbookType = 1,
		TextureId = 9541054718
	},
	{
		Type = "Slash",
		FlipbookType = 1,
		TextureId = 8821337290
	},
	{
		Type = "Slash",
		FlipbookType = 1,
		TextureId = 8944247946
	},
	{
		Type = "Slash",
		FlipbookType = 1,
		TextureId = 8618373035
	},
	{
		Type = "Slash",
		FlipbookType = 1,
		TextureId = 9670499279
	},
	{
		Type = "Slash",
		FlipbookType = 1,
		TextureId = 11669829539
	},
	{
		Type = "Slash",
		FlipbookType = 1,
		TextureId = 16511965818
	},
	{
		Type = "Slash",
		FlipbookType = 1,
		TextureId = 15232756680
	},
	{
		Type = "Slash",
		FlipbookType = 1,
		TextureId = 18450683871
	},
	{
		Type = "Slash",
		FlipbookType = 1,
		TextureId = 4543893907
	},
	{
		Type = "Slash",
		FlipbookType = 1,
		TextureId = 8187307109
	},
	{
		Type = "Slash",
		FlipbookType = 1,
		TextureId = 6246398215
	},
	{
		Type = "Slash",
		FlipbookType = 1,
		TextureId = 17612135754
	},
	{
		Type = "Slash",
		FlipbookType = 1,
		TextureId = 17612097993
	},
	{
		Type = "Slash",
		FlipbookType = 1,
		TextureId = 96351874787069
	},
	{
		Type = "Slash",
		FlipbookType = 1,
		TextureId = 87520821677529
	},
	{
		Type = "Slash",
		FlipbookType = 1,
		TextureId = 127353288690632
	},
	{
		Type = "Slash",
		FlipbookType = 1,
		TextureId = 9563708852
	},
	{
		Type = "Slash",
		FlipbookType = 1,
		TextureId = 11037286476
	},
	{
		Type = "Slash",
		FlipbookType = 1,
		TextureId = 10335159416
	},
	{
		Type = "Slash",
		FlipbookType = 1,
		TextureId = 7387037753
	},
	{
		Type = "Slash",
		FlipbookType = 1,
		TextureId = 7387058218
	},
	{
		Type = "Slash",
		FlipbookType = 1,
		TextureId = 14187131206
	},
	{
		Type = "Slash",
		FlipbookType = 1,
		TextureId = 16511969009
	},
	{
		Type = "Slash",
		FlipbookType = 1,
		TextureId = 15268221891
	},
	{
		Type = "Slash",
		FlipbookType = 1,
		TextureId = 18231592394
	},
	{
		Type = "Slash",
		FlipbookType = 1,
		TextureId = 15232758525
	},
	{
		Type = "Slash",
		FlipbookType = 1,
		TextureId = 17388445822
	},
	{
		Type = "Slash",
		FlipbookType = 1,
		TextureId = 18453224778
	},
	{
		Type = "Slash",
		FlipbookType = 1,
		TextureId = 8944260642
	},
	{
		Type = "Slash",
		FlipbookType = 1,
		TextureId = 14734941171
	},
	{
		Type = "Slash",
		FlipbookType = 1,
		TextureId = 19000059361
	},
	{
		Type = "Slash",
		FlipbookType = 1,
		TextureId = 9563708138
	},
	{
		Type = "Slash",
		FlipbookType = 1,
		TextureId = 13492803558
	},
	{
		Type = "Slash",
		FlipbookType = 1,
		TextureId = 8944257586
	},
	{
		Type = "Slash",
		FlipbookType = 1,
		TextureId = 18838818398
	},
	{
		Type = "Slash",
		FlipbookType = 1,
		TextureId = 17388444841
	},
	{
		Type = "Slash",
		FlipbookType = 1,
		TextureId = 3916186365
	},
	{
		Type = "Slash",
		FlipbookType = 1,
		TextureId = 12506449597
	},
	{
		Type = "Slash",
		FlipbookType = 1,
		TextureId = 13280169445
	},
	{
		Type = "Slash",
		FlipbookType = 1,
		TextureId = 1084963972
	},
	{
		Type = "Slash",
		FlipbookType = 1,
		TextureId = 376023896
	},
	{
		Type = "Slash",
		FlipbookType = 1,
		TextureId = 10927170198
	},
	{
		Type = "Slash",
		FlipbookType = 1,
		TextureId = 13580373276
	},
	{
		Type = "Slash",
		FlipbookType = 1,
		TextureId = 16520870801
	},
	{
		Type = "Slash",
		FlipbookType = 1,
		TextureId = 13695135137
	},
	{
		Type = "Slash",
		FlipbookType = 1,
		TextureId = 14734862876
	},
	{
		Type = "Slash",
		FlipbookType = 1,
		TextureId = 13556796799
	},
	{
		Type = "Slash",
		FlipbookType = 1,
		TextureId = 5726444189
	},
	{
		Type = "Slash",
		FlipbookType = 1,
		TextureId = 15268219678
	},
	{
		Type = "Slash",
		FlipbookType = 1,
		TextureId = 13367229656
	},
	{
		Type = "Slash",
		FlipbookType = 1,
		TextureId = 11192866186
	},
	{
		Type = "Slash",
		FlipbookType = 1,
		TextureId = 10558510611
	},
	{
		Type = "Slash",
		FlipbookType = 1,
		TextureId = 13539864728
	},
	{
		Type = "Slash",
		FlipbookType = 1,
		TextureId = 7216847656
	},
	{
		Type = "Slash",
		FlipbookType = 1,
		TextureId = 13280160427
	},
	{
		Type = "Slash",
		FlipbookType = 1,
		TextureId = 17388366674
	},
	{
		Type = "Slash",
		FlipbookType = 1,
		TextureId = 17388365582
	},
	{
		Type = "Slash",
		FlipbookType = 1,
		TextureId = 6863041721
	},
	{
		Type = "Slash",
		FlipbookType = 1,
		TextureId = 14197927959
	},
	{
		Type = "Slash",
		FlipbookType = 1,
		TextureId = 7216852306
	},
	{
		Type = "Slash",
		FlipbookType = 1,
		TextureId = 18450708444
	},
	{
		Type = "Slash",
		FlipbookType = 1,
		TextureId = 12491910393
	},
	{
		Type = "Slash",
		FlipbookType = 1,
		TextureId = 15268220856
	},
	{
		Type = "Slash",
		FlipbookType = 1,
		TextureId = 12470406098
	},
	{
		Type = "Slash",
		FlipbookType = 1,
		TextureId = 13280151063
	},
	{
		Type = "Slash",
		FlipbookType = 1,
		TextureId = 15190416756
	},
	{
		Type = "Slash",
		FlipbookType = 1,
		TextureId = 12402891438
	},
	{
		Type = "Slash",
		FlipbookType = 1,
		TextureId = 10031303479
	},
	{
		Type = "Slash",
		FlipbookType = 1,
		TextureId = 16310651343
	},
	{
		Type = "Slash",
		FlipbookType = 1,
		TextureId = 5700002424
	},
	{
		Type = "Slash",
		FlipbookType = 1,
		TextureId = 11636552631
	},
	{
		Type = "Slash",
		FlipbookType = 1,
		TextureId = 7265755321
	},
	{
		Type = "Slash",
		FlipbookType = 1,
		TextureId = 11037069395
	},
	{
		Type = "Slash",
		FlipbookType = 1,
		TextureId = 10263067827
	},
	{
		Type = "Slash",
		FlipbookType = 1,
		TextureId = 15232761257
	},
	{
		Type = "Slash",
		FlipbookType = 1,
		TextureId = 13366360838
	},
	{
		Type = "Slash",
		FlipbookType = 1,
		TextureId = 6700009083
	},
	{
		Type = "Slash",
		FlipbookType = 1,
		TextureId = 13580369388
	},
	{
		Type = "Slash",
		FlipbookType = 1,
		TextureId = 6246398215
	},
	{
		Type = "Slash",
		FlipbookType = 1,
		TextureId = 13556694436
	},
	{
		Type = "Slash",
		FlipbookType = 1,
		TextureId = 7216847514
	},
	{
		Type = "Slash",
		FlipbookType = 1,
		TextureId = 108308650548778
	},
	{
		Type = "Slash",
		FlipbookType = 1,
		TextureId = 13366366767
	},
	{
		Type = "Slash",
		FlipbookType = 1,
		TextureId = 1266209505
	},
	{
		Type = "Slash",
		FlipbookType = 1,
		TextureId = 7216852121
	},
	{
		Type = "Slash",
		FlipbookType = 1,
		TextureId = 15149886056
	},
	{
		Type = "Slash",
		FlipbookType = 1,
		TextureId = 11037068537
	},
	{
		Type = "Slash",
		FlipbookType = 1,
		TextureId = 10558425570
	},
	{
		Type = "Slash",
		FlipbookType = 1,
		TextureId = 7415024711
	},
	{
		Type = "Slash",
		FlipbookType = 1,
		TextureId = 12104767407
	},
	{
		Type = "Slash",
		FlipbookType = 1,
		TextureId = 5700002681
	},
	{
		Type = "Slash",
		FlipbookType = 1,
		TextureId = 13580374991
	},
	{
		Type = "Slash",
		FlipbookType = 1,
		TextureId = 7216847765
	},
	{
		Type = "Slash",
		FlipbookType = 1,
		TextureId = 15270200015
	},
	{
		Type = "Slash",
		FlipbookType = 1,
		TextureId = 13388189030
	},
	{
		Type = "Slash",
		FlipbookType = 1,
		TextureId = 8047533775
	},
	{
		Type = "Slash",
		FlipbookType = 1,
		TextureId = 13556736725
	},
	{
		Type = "Slash",
		FlipbookType = 1,
		TextureId = 1266209745
	},
	{
		Type = "Slash",
		FlipbookType = 1,
		TextureId = 13272096695
	},
	{
		Type = "Slash",
		FlipbookType = 1,
		TextureId = 18625401193
	},
	{
		Type = "Slash",
		FlipbookType = 1,
		TextureId = 7848213224
	},
	{
		Type = "Slash",
		FlipbookType = 1,
		TextureId = 11037069779
	},
	{
		Type = "Slash",
		FlipbookType = 1,
		TextureId = 12402896266
	},
	{
		Type = "Slash",
		FlipbookType = 1,
		TextureId = 8819682608
	},
	{
		Type = "Slash",
		FlipbookType = 1,
		TextureId = 14221642318
	},
	{
		Type = "Slash",
		FlipbookType = 1,
		TextureId = 14163204987
	},
	{
		Type = "Slash",
		FlipbookType = 1,
		TextureId = 14054635072
	},
	{
		Type = "Slash",
		FlipbookType = 1,
		TextureId = 138761801923749
	},
	{
		Type = "Slash",
		FlipbookType = 1,
		TextureId = 8077816591
	},
	{
		Type = "Slash",
		FlipbookType = 1,
		TextureId = 8047796070
	},
	{
		Type = "Slash",
		FlipbookType = 1,
		TextureId = 7216852206
	},
	{
		Type = "Slash",
		FlipbookType = 1,
		TextureId = 4543893907
	},
	{
		Type = "Slash",
		FlipbookType = 1,
		TextureId = 13520098330
	},
	{
		Type = "Slash",
		FlipbookType = 1,
		TextureId = 13556793224
	},
	{
		Type = "Slash",
		FlipbookType = 1,
		TextureId = 13819755999
	},
	{
		Type = "Slash",
		FlipbookType = 1,
		TextureId = 7886908733
	},
	{
		Type = "Slash",
		FlipbookType = 1,
		TextureId = 12402858850
	},
	{
		Type = "Slash",
		FlipbookType = 1,
		TextureId = 12402894729
	},
	{
		Type = "Slash",
		FlipbookType = 1,
		TextureId = 7530718892
	},
	{
		Type = "Slash",
		FlipbookType = 1,
		TextureId = 1266209618
	},
	{
		Type = "Slash",
		FlipbookType = 1,
		TextureId = 9841238252
	},
	{
		Type = "Slash",
		FlipbookType = 1,
		TextureId = 11973936966
	},
	{
		Type = "Slash",
		FlipbookType = 1,
		TextureId = 14221277745
	},
	{
		Type = "Slash",
		FlipbookType = 1,
		TextureId = 13388206804
	},
	{
		Type = "Slash",
		FlipbookType = 1,
		TextureId = 13539863591
	},
	{
		Type = "Slash",
		FlipbookType = 1,
		TextureId = 7216852545
	}
}
