[package]
name = "mia-gobble/effect-designer-suite"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Seam = "miagobble/seam@1.0.0"
Jian = "miagobble/jian@0.1.1"
Oklab = "miagobble/oklab@1.0.0"